import {
  Issue,
  FieldOfficer,
  DashboardStats,
  AnalyticsData,
  Message,
  Conversation,
  IssueUpdate,
  OfficialUser,
  DirectConversation,
  DirectMessage,
  AppNotification,
  CitizenMessage,
  PublicIssue,
  DuplicateGroup,
} from './types';

// Varanasi coordinates: 25.3176, 82.9739
export const VARANASI_CENTER = { latitude: 25.3176, longitude: 82.9739 };

export const mockFieldOfficers: FieldOfficer[] = [
  {
    id: 'fo-1',
    name: 'Rajesh Kumar',
    email: 'rajesh.kumar@citycare.in',
    avatar: 'https://i.pravatar.cc/150?img=12',
    rating: 4.7,
    specializations: ['Pothole', 'Road Repair'],
    workloadPercentage: 45,
    activeIssues: 3,
    successRate: 92,
    lastActive: '2024-02-28T10:30:00Z',
    ward: 'Varanasi Zone',
  },
  {
    id: 'fo-2',
    name: 'Priya Singh',
    email: 'priya.singh@citycare.in',
    avatar: 'https://i.pravatar.cc/150?img=47',
    rating: 4.9,
    specializations: ['Street Light', 'Public Safety'],
    workloadPercentage: 30,
    activeIssues: 2,
    successRate: 96,
    lastActive: '2024-02-28T11:15:00Z',
    ward: 'Varanasi Zone',
  },
  {
    id: 'fo-3',
    name: 'Amit Verma',
    email: 'amit.verma@citycare.in',
    avatar: 'https://i.pravatar.cc/150?img=33',
    rating: 4.5,
    specializations: ['Drainage', 'Water Supply'],
    workloadPercentage: 65,
    activeIssues: 4,
    successRate: 88,
    lastActive: '2024-02-28T09:45:00Z',
    ward: 'Varanasi Zone',
  },
  {
    id: 'fo-4',
    name: 'Sunita Yadav',
    email: 'sunita.yadav@citycare.in',
    avatar: 'https://i.pravatar.cc/150?img=44',
    rating: 4.8,
    specializations: ['Waste Management', 'Park Maintenance'],
    workloadPercentage: 25,
    activeIssues: 2,
    successRate: 94,
    lastActive: '2024-02-28T10:00:00Z',
    ward: 'Varanasi Zone',
  },
  {
    id: 'fo-5',
    name: 'Vikram Mishra',
    email: 'vikram.mishra@citycare.in',
    avatar: 'https://i.pravatar.cc/150?img=15',
    rating: 4.3,
    specializations: ['Road Repair', 'Drainage'],
    workloadPercentage: 85,
    activeIssues: 5,
    successRate: 85,
    lastActive: '2024-02-28T08:30:00Z',
    ward: 'Varanasi Zone',
  },
  {
    id: 'fo-6',
    name: 'Anjali Sharma',
    email: 'anjali.sharma@citycare.in',
    avatar: 'https://i.pravatar.cc/150?img=38',
    rating: 4.6,
    specializations: ['Pothole', 'Street Light', 'Public Safety'],
    workloadPercentage: 40,
    activeIssues: 3,
    successRate: 90,
    lastActive: '2024-02-28T11:00:00Z',
    ward: 'Varanasi Zone',
  },
  {
    id: 'fo-7',
    name: 'Deepak Gupta',
    email: 'deepak.gupta@citycare.in',
    avatar: 'https://i.pravatar.cc/150?img=51',
    rating: 4.4,
    specializations: ['Road Repair', 'Pothole'],
    workloadPercentage: 55,
    activeIssues: 4,
    successRate: 87,
    lastActive: '2024-02-28T09:00:00Z',
    ward: 'Varanasi Zone',
  },
  {
    id: 'fo-8',
    name: 'Rekha Devi',
    email: 'rekha.devi@citycare.in',
    avatar: 'https://i.pravatar.cc/150?img=29',
    rating: 4.7,
    specializations: ['Waste Management', 'Drainage'],
    workloadPercentage: 35,
    activeIssues: 2,
    successRate: 93,
    lastActive: '2024-02-28T10:45:00Z',
    ward: 'Varanasi Zone',
  },
  {
    id: 'fo-9',
    name: 'Manoj Kumar',
    email: 'manoj.kumar@citycare.in',
    avatar: 'https://i.pravatar.cc/150?img=60',
    rating: 4.2,
    specializations: ['Street Light', 'Public Safety'],
    workloadPercentage: 70,
    activeIssues: 5,
    successRate: 84,
    lastActive: '2024-02-28T08:00:00Z',
    ward: 'Varanasi Zone',
  },
  {
    id: 'fo-10',
    name: 'Pooja Mishra',
    email: 'pooja.mishra@citycare.in',
    avatar: 'https://i.pravatar.cc/150?img=45',
    rating: 4.8,
    specializations: ['Water Supply', 'Park Maintenance'],
    workloadPercentage: 20,
    activeIssues: 1,
    successRate: 95,
    lastActive: '2024-02-28T11:30:00Z',
    ward: 'Varanasi Zone',
  },
];

export const mockIssues: Issue[] = [
  {
    id: 'ISS-2024-001',
    title: 'Large Pothole on Assi Ghat Road',
    description:
      'Deep pothole causing traffic disruption and risk to two-wheelers. Water accumulation during rain makes it extremely dangerous, especially at night. Multiple vehicles have been damaged in the past week.',
    category: 'Pothole',
    subCategories: ['Major Pothole', 'Road Cave-in'],
    tags: ['#urgent', '#pothole', '#traffichazard', '#roadrepair', '#varanasi'],
    priority: 'High',
    status: 'Pending',
    location: 'Assi Ghat Road, Near Tulsi Ghat',
    ward: 'Varanasi Zone',
    citizenName: 'Ramesh Pandey',
    citizenEmail: 'ramesh.pandey@gmail.com',
    citizenPhone: '+91 9876543210',
    dateReported: '2024-02-27T14:30:00Z',
    beforePhotos: [
      'https://images.pexels.com/photos/416430/pexels-photo-416430.jpeg',
      'https://images.pexels.com/photos/1563256/pexels-photo-1563256.jpeg',
      'https://images.pexels.com/photos/2219024/pexels-photo-2219024.jpeg',
    ],
    videoEvidence: ['https://www.w3schools.com/html/mov_bbb.mp4'],
    issueUpdates: [
      {
        id: 'upd-1',
        issueId: 'ISS-2024-001',
        status: 'Pending',
        comment:
          'Issue reported by citizen. Deep pothole spotted on Assi Ghat Road near Tulsi Ghat.',
        role: 'Citizen',
        attachments: ['https://images.pexels.com/photos/416430/pexels-photo-416430.jpeg'],
        updatedBy: 'citizen-1',
        scope: 'citizen',
        createdAt: '2024-02-27T14:30:00Z',
      },
    ],
    coordinates: { latitude: 25.282, longitude: 82.9897 },
    createdAt: '2024-02-27T14:30:00Z',
    images: [
      'https://images.pexels.com/photos/416430/pexels-photo-416430.jpeg',
      'https://images.pexels.com/photos/1563256/pexels-photo-1563256.jpeg',
      'https://images.pexels.com/photos/2219024/pexels-photo-2219024.jpeg',
      'https://images.pexels.com/photos/1670732/pexels-photo-1670732.jpeg',
      'https://images.pexels.com/photos/2768973/pexels-photo-2768973.jpeg',
    ],
  },
  {
    id: 'ISS-2024-002',
    title: 'Street Light Not Working - Godowlia',
    description:
      'Multiple street lights not functioning for over a week. Safety concern for evening traffic.',
    category: 'Street Light',
    subCategories: ['Street Light Out', 'Damaged Pole'],
    tags: ['#publicsafety', '#streetlight', '#nightsafety', '#critical', '#godowlia'],
    priority: 'Critical',
    status: 'Verified',
    location: 'Godowlia Chowk',
    ward: 'Varanasi Zone',
    citizenName: 'Sanjay Gupta',
    citizenEmail: 'sanjay.gupta@gmail.com',
    citizenPhone: '+91 9876543211',
    dateReported: '2024-02-26T18:45:00Z',
    beforePhotos: [
      'https://images.pexels.com/photos/1112048/pexels-photo-1112048.jpeg',
      'https://images.pexels.com/photos/280221/pexels-photo-280221.jpeg',
    ],
    videoEvidence: ['https://www.w3schools.com/html/mov_bbb.mp4'],
    issueUpdates: [
      {
        id: 'upd-2',
        issueId: 'ISS-2024-002',
        status: 'Pending',
        comment: 'Multiple street lights are out at Godowlia Chowk. Reported by local resident.',
        role: 'Citizen',
        attachments: ['https://images.pexels.com/photos/1112048/pexels-photo-1112048.jpeg'],
        updatedBy: 'citizen-2',
        scope: 'citizen',
        createdAt: '2024-02-26T18:45:00Z',
      },
      {
        id: 'upd-3',
        issueId: 'ISS-2024-002',
        status: 'Verified',
        comment: 'Verified on-site. Two poles confirmed damaged. Forwarding to electrical dept.',
        role: 'UnitOfficer',
        attachments: [],
        updatedBy: 'uo-1',
        scope: 'field_and_citizen',
        createdAt: '2024-02-27T09:00:00Z',
      },
    ],
    slaDeadline: '2026-04-15T23:59:59Z',
    coordinates: { latitude: 25.3108, longitude: 83.0107 },
    createdAt: '2024-02-26T18:45:00Z',
    images: [
      'https://images.pexels.com/photos/1112048/pexels-photo-1112048.jpeg',
      'https://images.pexels.com/photos/280221/pexels-photo-280221.jpeg',
      'https://images.pexels.com/photos/1536988/pexels-photo-1536988.jpeg',
      'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg',
    ],
    verificationChecklist: {
      locationValid: true,
      evidenceSufficient: true,
      notDuplicate: true,
      withinJurisdiction: true,
    },
  },
  {
    id: 'ISS-2024-003',
    title: 'Overflowing Garbage Bins - Dashashwamedh',
    description:
      'Waste bins overflowing for 3 days. Creating hygiene issues and attracting stray animals.',
    category: 'Waste Management',
    subCategories: ['Garbage Overflow', 'Illegal Dumping'],
    tags: ['#hygiene', '#wastemanagement', '#strayanimals', '#ghats', '#dashashwamedh'],
    priority: 'High',
    status: 'Assigned',
    location: 'Dashashwamedh Ghat Area',
    ward: 'Varanasi Zone',
    citizenName: 'Meera Devi',
    citizenEmail: 'meera.devi@gmail.com',
    citizenPhone: '+91 9876543212',
    dateReported: '2024-02-25T11:20:00Z',
    assignedOfficer: 'Sunita Yadav',
    assignedOfficerId: 'fo-4',
    beforePhotos: ['https://images.pexels.com/photos/128421/pexels-photo-128421.jpeg'],
    issueUpdates: [
      {
        id: 'upd-4',
        issueId: 'ISS-2024-003',
        status: 'Pending',
        comment:
          'Garbage bins overflowing near Dashashwamedh Ghat for 3 days. Stray animals gathering.',
        role: 'Citizen',
        attachments: ['https://images.pexels.com/photos/128421/pexels-photo-128421.jpeg'],
        updatedBy: 'citizen-3',
        scope: 'citizen',
        createdAt: '2024-02-25T11:20:00Z',
      },
      {
        id: 'upd-5',
        issueId: 'ISS-2024-003',
        status: 'Verified',
        comment: 'Confirmed. Overflow from 4 bins. Health hazard noted. Assigning cleanup team.',
        role: 'UnitOfficer',
        attachments: [],
        updatedBy: 'uo-1',
        scope: 'field_and_citizen',
        createdAt: '2024-02-25T15:00:00Z',
      },
      {
        id: 'upd-6',
        issueId: 'ISS-2024-003',
        status: 'Assigned',
        comment: 'Assigned to Sunita Yadav for same-day clearance. Priority elevated.',
        role: 'UnitOfficer',
        attachments: [],
        updatedBy: 'uo-1',
        scope: 'field_and_citizen',
        createdAt: '2024-02-26T10:00:00Z',
      },
    ],
    slaDeadline: '2026-04-10T23:59:59Z',
    coordinates: { latitude: 25.3069, longitude: 83.0102 },
    createdAt: '2024-02-25T11:20:00Z',
    images: [
      'https://images.pexels.com/photos/128421/pexels-photo-128421.jpeg',
      'https://images.pexels.com/photos/2768973/pexels-photo-2768973.jpeg',
      'https://images.pexels.com/photos/1301856/pexels-photo-1301856.jpeg',
    ],
    videoEvidence: ['https://www.w3schools.com/html/mov_bbb.mp4'],
  },
  {
    id: 'ISS-2024-004',
    title: 'Drainage Blockage - Lanka',
    description:
      'Severe drainage blockage causing water logging during rain. Affecting 10+ households.',
    category: 'Drainage',
    subCategories: ['Drain Overflow', 'Blocked Drain'],
    tags: ['#waterlogging', '#drainage', '#bhuroand', '#flooding', '#critical'],
    priority: 'Critical',
    status: 'In Progress',
    location: 'Lanka, BHU Road',
    ward: 'Varanasi Zone',
    citizenName: 'Rajiv Tiwari',
    citizenEmail: 'rajiv.tiwari@gmail.com',
    citizenPhone: '+91 9876543213',
    dateReported: '2024-02-24T08:00:00Z',
    assignedOfficer: 'Amit Verma',
    assignedOfficerId: 'fo-3',
    beforePhotos: ['https://images.pexels.com/photos/2768973/pexels-photo-2768973.jpeg'],
    issueUpdates: [
      {
        id: 'upd-7',
        issueId: 'ISS-2024-004',
        status: 'Pending',
        comment: 'Severe drain blockage on Lanka BHU Road. Water logging in front of 10+ houses.',
        role: 'Citizen',
        attachments: ['https://images.pexels.com/photos/2768973/pexels-photo-2768973.jpeg'],
        updatedBy: 'citizen-4',
        scope: 'citizen',
        createdAt: '2024-02-24T08:00:00Z',
      },
      {
        id: 'upd-8',
        issueId: 'ISS-2024-004',
        status: 'Verified',
        comment:
          'Site inspected. Blockage confirmed at main junction drain. Urgent clearance needed.',
        role: 'UnitOfficer',
        attachments: [],
        updatedBy: 'uo-1',
        scope: 'field_and_citizen',
        createdAt: '2024-02-24T11:00:00Z',
      },
      {
        id: 'upd-9',
        issueId: 'ISS-2024-004',
        status: 'Assigned',
        comment: 'Assigned to Amit Verma. Drainage equipment dispatched.',
        role: 'UnitOfficer',
        attachments: [],
        updatedBy: 'uo-1',
        scope: 'field_and_citizen',
        createdAt: '2024-02-25T09:00:00Z',
      },
      {
        id: 'upd-10',
        issueId: 'ISS-2024-004',
        status: 'In Progress',
        comment:
          'Desilting work underway. Expect completion in 6 hours. Road is partially accessible.',
        role: 'FieldOfficer',
        attachments: ['https://images.pexels.com/photos/2219024/pexels-photo-2219024.jpeg'],
        updatedBy: 'fo-3',
        scope: 'field_and_citizen',
        createdAt: '2024-02-26T10:00:00Z',
      },
    ],
    slaDeadline: '2026-04-08T23:59:59Z',
    coordinates: { latitude: 25.2677, longitude: 82.9913 },
    createdAt: '2024-02-24T08:00:00Z',
    images: ['https://images.pexels.com/photos/2768973/pexels-photo-2768973.jpeg'],
  },
  {
    id: 'ISS-2024-005',
    title: 'Road Repair Needed - Sigra',
    description: 'Road surface deteriorated with multiple cracks. Needs urgent resurfacing work.',
    category: 'Road Repair',
    subCategories: ['Footpath Damage', 'Median Damage'],
    tags: ['#roadrepair', '#sigra', '#resurfacing', '#infrastructure', '#pendingverification'],
    priority: 'Medium',
    status: 'Pending UO Verification',
    location: 'Sigra Main Road',
    ward: 'Varanasi Zone',
    citizenName: 'Anita Sharma',
    citizenEmail: 'anita.sharma@gmail.com',
    citizenPhone: '+91 9876543214',
    dateReported: '2024-02-22T16:30:00Z',
    assignedOfficer: 'Rajesh Kumar',
    assignedOfficerId: 'fo-1',
    beforePhotos: ['https://images.pexels.com/photos/1670732/pexels-photo-1670732.jpeg'],
    afterPhotos: ['https://images.pexels.com/photos/2219024/pexels-photo-2219024.jpeg'],
    issueUpdates: [
      {
        id: 'upd-11',
        issueId: 'ISS-2024-005',
        status: 'Pending',
        comment: 'Sigra Main Road has multiple cracks and potholes. Needs urgent resurfacing.',
        role: 'Citizen',
        attachments: ['https://images.pexels.com/photos/1670732/pexels-photo-1670732.jpeg'],
        updatedBy: 'citizen-5',
        scope: 'citizen',
        createdAt: '2024-02-22T16:30:00Z',
      },
      {
        id: 'upd-12',
        issueId: 'ISS-2024-005',
        status: 'Verified',
        comment: 'Road surface verified. Cracks span over 50 metres. Approved for repair.',
        role: 'UnitOfficer',
        attachments: [],
        updatedBy: 'uo-1',
        scope: 'field_and_citizen',
        createdAt: '2024-02-23T09:00:00Z',
      },
      {
        id: 'upd-13',
        issueId: 'ISS-2024-005',
        status: 'Assigned',
        comment: 'Rajesh Kumar assigned. Material procurement underway.',
        role: 'UnitOfficer',
        attachments: [],
        updatedBy: 'uo-1',
        scope: 'admin_only',
        createdAt: '2024-02-23T14:00:00Z',
      },
      {
        id: 'upd-14',
        issueId: 'ISS-2024-005',
        status: 'In Progress',
        comment: 'Resurfacing started. Bitumen mix applied on first 20 metres.',
        role: 'FieldOfficer',
        attachments: ['https://images.pexels.com/photos/1563256/pexels-photo-1563256.jpeg'],
        updatedBy: 'fo-1',
        scope: 'field_and_citizen',
        createdAt: '2024-02-24T08:00:00Z',
      },
      {
        id: 'upd-15',
        issueId: 'ISS-2024-005',
        status: 'Pending UO Verification',
        comment:
          'Road surface repaired and sealed. Used premium quality materials. Quality check recommended.',
        role: 'FieldOfficer',
        attachments: ['https://images.pexels.com/photos/2219024/pexels-photo-2219024.jpeg'],
        updatedBy: 'fo-1',
        scope: 'field_and_citizen',
        createdAt: '2024-02-27T16:00:00Z',
      },
    ],
    slaDeadline: '2026-04-20T23:59:59Z',
    coordinates: { latitude: 25.2744, longitude: 82.988 },
    createdAt: '2024-02-22T16:30:00Z',
    images: ['https://images.pexels.com/photos/1670732/pexels-photo-1670732.jpeg'],
    submissionComment: 'Road surface repaired and sealed. Used premium quality materials.',
    submissionLocation: { latitude: 25.2744, longitude: 82.988 },
    submissionTimestamp: '2024-02-27T16:00:00Z',
    foResolutionDescription:
      'Completed full resurfacing of Sigra Main Road covering 60 metres. Applied bitumen mix grade VG-30, compacted with vibratory roller. Road markings re-painted. Surface is smooth and ready for traffic. Used premium quality materials as per municipal standards.',
    foBeforeLocation: { latitude: 25.2746, longitude: 82.9882, timestamp: '2024-02-24T07:50:00Z' },
    foAfterLocation: { latitude: 25.2745, longitude: 82.9881, timestamp: '2024-02-27T15:55:00Z' },
  },
  {
    id: 'ISS-2024-006',
    title: 'Water Leak - Sunderpur',
    description:
      'Major water leak from main supply line. Water wastage and potential damage to nearby structures.',
    category: 'Water Supply',
    subCategories: ['Water Leakage'],
    tags: ['#waterleak', '#watersupply', '#sunderpur', '#rework', '#urgent'],
    priority: 'High',
    status: 'Rework Required',
    location: 'Sunderpur Colony',
    ward: 'Varanasi Zone',
    citizenName: 'Prakash Yadav',
    citizenEmail: 'prakash.yadav@gmail.com',
    citizenPhone: '+91 9876543215',
    dateReported: '2024-02-20T07:15:00Z',
    assignedOfficer: 'Amit Verma',
    assignedOfficerId: 'fo-3',
    beforePhotos: ['https://images.pexels.com/photos/4033111/pexels-photo-4033111.jpeg'],
    afterPhotos: ['https://images.pexels.com/photos/1416530/pexels-photo-1416530.jpeg'],
    issueUpdates: [
      {
        id: 'upd-16',
        issueId: 'ISS-2024-006',
        status: 'Pending',
        comment:
          'Water leaking from main supply line in Sunderpur Colony. Road getting waterlogged.',
        role: 'Citizen',
        attachments: ['https://images.pexels.com/photos/4033111/pexels-photo-4033111.jpeg'],
        updatedBy: 'citizen-6',
        scope: 'citizen',
        createdAt: '2024-02-20T07:15:00Z',
      },
      {
        id: 'upd-17',
        issueId: 'ISS-2024-006',
        status: 'Verified',
        comment:
          'Leak verified at joint near meter box. High flow rate. Immediate action required.',
        role: 'UnitOfficer',
        attachments: [],
        updatedBy: 'uo-1',
        scope: 'field_and_citizen',
        createdAt: '2024-02-20T10:00:00Z',
      },
      {
        id: 'upd-18',
        issueId: 'ISS-2024-006',
        status: 'Assigned',
        comment: 'Amit Verma assigned. Pipe repair team notified.',
        role: 'UnitOfficer',
        attachments: [],
        updatedBy: 'uo-1',
        scope: 'admin_only',
        createdAt: '2024-02-21T09:00:00Z',
      },
      {
        id: 'upd-19',
        issueId: 'ISS-2024-006',
        status: 'In Progress',
        comment: 'Excavation done. Pipe exposed. Joint repair in progress.',
        role: 'FieldOfficer',
        attachments: ['https://images.pexels.com/photos/1416530/pexels-photo-1416530.jpeg'],
        updatedBy: 'fo-3',
        scope: 'field_and_citizen',
        createdAt: '2024-02-22T08:00:00Z',
      },
      {
        id: 'upd-20',
        issueId: 'ISS-2024-006',
        status: 'Pending UO Verification',
        comment: 'Pipe joint replaced and sealed. Water supply restored. Area backfilled.',
        role: 'FieldOfficer',
        attachments: [],
        updatedBy: 'fo-3',
        scope: 'field_and_citizen',
        createdAt: '2024-02-25T15:00:00Z',
      },
      {
        id: 'upd-21',
        issueId: 'ISS-2024-006',
        status: 'Rework Required',
        comment:
          'Seepage still visible at the old joint location. Needs full pipe replacement not just sealing.',
        role: 'UnitOfficer',
        attachments: [],
        updatedBy: 'uo-1',
        scope: 'field_and_citizen',
        createdAt: '2024-02-26T11:00:00Z',
      },
    ],
    slaDeadline: '2026-04-12T23:59:59Z',
    coordinates: { latitude: 25.295, longitude: 82.985 },
    createdAt: '2024-02-20T07:15:00Z',
    images: ['https://images.pexels.com/photos/4033111/pexels-photo-4033111.jpeg'],
    reworkReason: 'Incomplete fix',
    reworkComment: 'Leak still visible at the joint. Needs proper sealing and pressure test.',
  },
  {
    id: 'ISS-2024-007',
    title: 'Park Maintenance - Ravidas Park',
    description:
      'Broken benches, overgrown vegetation, and damaged walkway. Park needs comprehensive maintenance. Issue was initially closed but re-opened by citizen after finding two benches near the east gate still broken and unreplaced.',
    category: 'Park Maintenance',
    subCategories: ['Equipment Broken', 'Tree Fallen'],
    tags: ['#parkmaintenance', '#ravidaspark', '#benches', '#greenery', '#reopened'],
    priority: 'Medium',
    status: 'Reopened',
    location: 'Ravidas Park, East Gate Section, Khojwa',
    ward: 'Varanasi Zone',
    citizenName: 'Kavita Singh',
    citizenEmail: 'kavita.singh@gmail.com',
    citizenPhone: '+91 9876543216',
    dateReported: '2024-02-15T10:00:00Z',
    assignedOfficer: 'Sunita Yadav',
    assignedOfficerId: 'fo-4',
    beforePhotos: [
      'https://images.pexels.com/photos/1301856/pexels-photo-1301856.jpeg',
      'https://images.pexels.com/photos/1179229/pexels-photo-1179229.jpeg',
    ],
    afterPhotos: ['https://images.pexels.com/photos/1105766/pexels-photo-1105766.jpeg'],
    issueUpdates: [
      {
        id: 'upd-22',
        issueId: 'ISS-2024-007',
        status: 'Pending',
        comment:
          'Benches broken, walkway damaged, and heavy overgrowth in Ravidas Park, Khojwa. At least 6 benches are unusable and the east gate path has deep cracks.',
        role: 'Citizen',
        attachments: ['https://images.pexels.com/photos/1301856/pexels-photo-1301856.jpeg'],
        updatedBy: 'citizen-7',
        scope: 'citizen',
        createdAt: '2024-02-15T10:00:00Z',
      },
      {
        id: 'upd-23',
        issueId: 'ISS-2024-007',
        status: 'Verified',
        comment:
          'Site inspected. Confirmed: 6 benches broken (4 in central area, 2 near east gate), main walkway cracked in 3 sections, tree branches overhanging path. SLA set to 10 days.',
        role: 'UnitOfficer',
        attachments: [],
        updatedBy: 'uo-1',
        scope: 'field_and_citizen',
        createdAt: '2024-02-16T09:00:00Z',
      },
      {
        id: 'upd-24',
        issueId: 'ISS-2024-007',
        status: 'Assigned',
        comment:
          'Sunita Yadav assigned for park maintenance. Maintenance crew of 4 allocated for 2 days. Material procurement order raised.',
        role: 'UnitOfficer',
        attachments: [],
        updatedBy: 'uo-1',
        scope: 'admin_only',
        createdAt: '2024-02-17T10:00:00Z',
      },
      {
        id: 'upd-25',
        issueId: 'ISS-2024-007',
        status: 'In Progress',
        comment:
          'Tree trimming completed. Walkway patching underway — 2 of 3 crack sections sealed. Replacement benches received, installation begins tomorrow.',
        role: 'FieldOfficer',
        attachments: ['https://images.pexels.com/photos/1105766/pexels-photo-1105766.jpeg'],
        updatedBy: 'fo-4',
        scope: 'field_and_citizen',
        createdAt: '2024-02-18T08:00:00Z',
      },
      {
        id: 'upd-26',
        issueId: 'ISS-2024-007',
        status: 'Pending UO Verification',
        comment:
          'Walkway fully repaired across all 3 sections, trees trimmed and waste cleared, 4 benches replaced in the central area. Submitted for final inspection.',
        role: 'FieldOfficer',
        attachments: ['https://images.pexels.com/photos/1301856/pexels-photo-1301856.jpeg'],
        updatedBy: 'fo-4',
        scope: 'field_and_citizen',
        createdAt: '2024-02-22T16:00:00Z',
      },
      {
        id: 'upd-27',
        issueId: 'ISS-2024-007',
        status: 'Closed',
        comment:
          'Site inspection completed. Walkway repairs and tree trimming verified satisfactory. 4 benches replaced and confirmed functional. Issue marked closed.',
        role: 'UnitOfficer',
        attachments: [],
        updatedBy: 'uo-1',
        scope: 'citizen',
        createdAt: '2024-02-23T10:00:00Z',
      },
      {
        id: 'upd-28',
        issueId: 'ISS-2024-007',
        status: 'Reopened',
        comment:
          'Re-opening this issue. Two benches near the east gate are still broken and have not been replaced. I have attached photos as evidence. The officer only replaced 4 benches in the central area but ignored the 2 east gate benches mentioned in the original report.',
        role: 'Citizen',
        attachments: ['https://images.pexels.com/photos/1179229/pexels-photo-1179229.jpeg'],
        updatedBy: 'citizen-7',
        scope: 'citizen',
        createdAt: '2024-02-26T14:00:00Z',
      },
    ],
    slaDeadline: '2026-04-25T23:59:59Z',
    coordinates: { latitude: 25.288, longitude: 82.995 },
    createdAt: '2024-02-15T10:00:00Z',
    images: [
      'https://images.pexels.com/photos/1301856/pexels-photo-1301856.jpeg',
      'https://images.pexels.com/photos/1179229/pexels-photo-1179229.jpeg',
    ],
  },
  {
    id: 'ISS-2024-008',
    title: 'Traffic Safety Issue - Bhelupur',
    description: 'Faded road markings and missing speed breaker sign. Safety hazard for vehicles.',
    category: 'Public Safety',
    subCategories: ['Noise Complaint', 'Encroachment'],
    tags: ['#publicsafety', '#trafficsafety', '#escalated', '#bhelupur', '#slabreach'],
    priority: 'High',
    status: 'Escalated',
    location: 'Bhelupur Crossing',
    ward: 'Varanasi Zone',
    citizenName: 'Suresh Patel',
    citizenEmail: 'suresh.patel@gmail.com',
    citizenPhone: '+91 9876543217',
    dateReported: '2024-02-18T13:00:00Z',
    assignedOfficer: 'Priya Singh',
    assignedOfficerId: 'fo-2',
    beforePhotos: ['https://images.pexels.com/photos/2764678/pexels-photo-2764678.jpeg'],
    issueUpdates: [
      {
        id: 'upd-29',
        issueId: 'ISS-2024-008',
        status: 'Pending',
        comment:
          'Road markings faded and speed breaker sign missing at Bhelupur Crossing. Dangerous for vehicles.',
        role: 'Citizen',
        attachments: ['https://images.pexels.com/photos/2764678/pexels-photo-2764678.jpeg'],
        updatedBy: 'citizen-8',
        scope: 'citizen',
        createdAt: '2024-02-18T13:00:00Z',
      },
      {
        id: 'upd-30',
        issueId: 'ISS-2024-008',
        status: 'Verified',
        comment:
          'Verified. Missing signage and complete fade of zebra crossing lines. High risk crossing.',
        role: 'UnitOfficer',
        attachments: [],
        updatedBy: 'uo-1',
        scope: 'field_and_citizen',
        createdAt: '2024-02-19T09:00:00Z',
      },
      {
        id: 'upd-31',
        issueId: 'ISS-2024-008',
        status: 'Assigned',
        comment: 'Priya Singh assigned. Traffic dept coordination pending.',
        role: 'UnitOfficer',
        attachments: [],
        updatedBy: 'uo-1',
        scope: 'admin_only',
        createdAt: '2024-02-19T14:00:00Z',
      },
      {
        id: 'upd-32',
        issueId: 'ISS-2024-008',
        status: 'In Progress',
        comment: 'Contacted traffic department. Awaiting paint supply and signage materials.',
        role: 'FieldOfficer',
        attachments: [],
        updatedBy: 'fo-2',
        scope: 'field_and_citizen',
        createdAt: '2024-02-20T08:00:00Z',
      },
      {
        id: 'upd-33',
        issueId: 'ISS-2024-008',
        status: 'Escalated',
        comment:
          'SLA breached. Requires formal traffic department approval and police coordination. Escalated to Admin.',
        role: 'UnitOfficer',
        attachments: [],
        updatedBy: 'uo-1',
        scope: 'admin_only',
        createdAt: '2024-02-25T10:00:00Z',
      },
    ],
    slaDeadline: '2026-04-05T23:59:59Z',
    coordinates: { latitude: 25.2789, longitude: 82.9823 },
    createdAt: '2024-02-18T13:00:00Z',
    images: ['https://images.pexels.com/photos/2764678/pexels-photo-2764678.jpeg'],
    escalationReason: 'SLA breach',
    escalationComment:
      'Requires traffic department coordination and police approval. Beyond field officer scope.',
  },
  {
    id: 'ISS-2024-009',
    title: 'Broken Drain Cover - Maldahiya',
    description: 'Drain cover missing creating safety hazard for pedestrians and vehicles.',
    category: 'Drainage',
    subCategories: ['Blocked Drain'],
    tags: ['#draincover', '#pedestriansafety', '#maldahiya', '#closed', '#hazard'],
    priority: 'Critical',
    status: 'Closed',
    location: 'Maldahiya Main Road',
    ward: 'Varanasi Zone',
    citizenName: 'Neha Gupta',
    citizenEmail: 'neha.gupta@gmail.com',
    citizenPhone: '+91 9876543218',
    dateReported: '2024-02-10T09:30:00Z',
    assignedOfficer: 'Amit Verma',
    assignedOfficerId: 'fo-3',
    beforePhotos: ['https://images.pexels.com/photos/1133505/pexels-photo-1133505.jpeg'],
    afterPhotos: ['https://images.pexels.com/photos/1262304/pexels-photo-1262304.jpeg'],
    issueUpdates: [
      {
        id: 'upd-34',
        issueId: 'ISS-2024-009',
        status: 'Pending',
        comment: 'Drain cover missing on Maldahiya Main Road. Pedestrian fell nearby yesterday.',
        role: 'Citizen',
        attachments: ['https://images.pexels.com/photos/1133505/pexels-photo-1133505.jpeg'],
        updatedBy: 'citizen-9',
        scope: 'citizen',
        createdAt: '2024-02-10T09:30:00Z',
      },
      {
        id: 'upd-35',
        issueId: 'ISS-2024-009',
        status: 'Verified',
        comment:
          'Missing drain cover confirmed. Hazard barricaded temporarily. Urgent replacement needed.',
        role: 'UnitOfficer',
        attachments: [],
        updatedBy: 'uo-1',
        scope: 'field_and_citizen',
        createdAt: '2024-02-10T14:00:00Z',
      },
      {
        id: 'upd-36',
        issueId: 'ISS-2024-009',
        status: 'Assigned',
        comment: 'Amit Verma assigned. Cast iron cover ordered from municipal store.',
        role: 'UnitOfficer',
        attachments: [],
        updatedBy: 'uo-1',
        scope: 'admin_only',
        createdAt: '2024-02-11T09:00:00Z',
      },
      {
        id: 'upd-37',
        issueId: 'ISS-2024-009',
        status: 'In Progress',
        comment: 'New drain cover received. Fitting work in progress.',
        role: 'FieldOfficer',
        attachments: ['https://images.pexels.com/photos/1262304/pexels-photo-1262304.jpeg'],
        updatedBy: 'fo-3',
        scope: 'field_and_citizen',
        createdAt: '2024-02-12T08:00:00Z',
      },
      {
        id: 'upd-38',
        issueId: 'ISS-2024-009',
        status: 'Pending UO Verification',
        comment: 'Drain cover installed and secured. Road cleared and safe for pedestrians.',
        role: 'FieldOfficer',
        attachments: ['https://images.pexels.com/photos/1262304/pexels-photo-1262304.jpeg'],
        updatedBy: 'fo-3',
        scope: 'field_and_citizen',
        createdAt: '2024-02-14T15:00:00Z',
      },
      {
        id: 'upd-39',
        issueId: 'ISS-2024-009',
        status: 'Closed',
        comment: 'Drain cover verified and properly installed. Issue resolved and closed.',
        role: 'UnitOfficer',
        attachments: [],
        updatedBy: 'uo-1',
        scope: 'citizen',
        createdAt: '2024-02-15T10:00:00Z',
      },
    ],
    slaDeadline: '2026-04-18T23:59:59Z',
    coordinates: { latitude: 25.32, longitude: 82.97 },
    createdAt: '2024-02-10T09:30:00Z',
    images: ['https://images.pexels.com/photos/1133505/pexels-photo-1133505.jpeg'],
  },
  {
    id: 'ISS-2024-010',
    title: 'Duplicate Report - Test',
    description: 'This is a duplicate issue for testing rejection flow.',
    category: 'Pothole',
    subCategories: ['Minor Pothole'],
    tags: ['#duplicate', '#rejected', '#test'],
    priority: 'Low',
    status: 'Rejected',
    location: 'Test Location',
    ward: 'Varanasi Zone',
    citizenName: 'Test User',
    citizenEmail: 'test@test.com',
    citizenPhone: '+91 9999999999',
    dateReported: '2024-02-27T12:00:00Z',
    beforePhotos: [],
    issueUpdates: [
      {
        id: 'upd-40',
        issueId: 'ISS-2024-010',
        status: 'Pending',
        comment: 'Pothole reported at test location.',
        role: 'Citizen',
        attachments: [],
        updatedBy: 'citizen-10',
        scope: 'citizen',
        createdAt: '2024-02-27T12:00:00Z',
      },
      {
        id: 'upd-41',
        issueId: 'ISS-2024-010',
        status: 'Rejected',
        comment: 'Duplicate of ISS-2024-001 which is already being processed. Closing this report.',
        role: 'UnitOfficer',
        attachments: [],
        updatedBy: 'uo-1',
        scope: 'citizen',
        createdAt: '2024-02-27T13:00:00Z',
      },
    ],
    coordinates: { latitude: 25.3176, longitude: 82.9739 },
    createdAt: '2024-02-27T12:00:00Z',
    images: [],
    rejectionReason: 'Duplicate',
    rejectionComment: 'This issue is a duplicate of ISS-2024-001 already being processed.',
  },
  {
    id: 'ISS-2024-011',
    title: 'Broken Street Light - Nadesar',
    description:
      'Two street lights non-functional near Nadesar Palace road. Residents face safety issues at night.',
    category: 'Street Light',
    subCategories: ['Street Light Out', 'Damaged Pole'],
    tags: ['#streetlight', '#nadesar', '#nightsafety', '#pendingverification'],
    priority: 'High',
    status: 'Pending UO Verification',
    location: 'Nadesar Palace Road, Near Hotel Taj',
    ward: 'Varanasi Zone',
    citizenName: 'Vinod Tripathi',
    citizenEmail: 'vinod.tripathi@gmail.com',
    citizenPhone: '+91 9876543220',
    dateReported: '2024-02-26T08:00:00Z',
    assignedOfficer: 'Priya Singh',
    assignedOfficerId: 'fo-2',
    beforePhotos: [
      'https://images.pexels.com/photos/1112048/pexels-photo-1112048.jpeg',
      'https://images.pexels.com/photos/280221/pexels-photo-280221.jpeg',
    ],
    afterPhotos: [
      'https://images.pexels.com/photos/1536988/pexels-photo-1536988.jpeg',
      'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg',
    ],
    issueUpdates: [
      {
        id: 'upd-50',
        issueId: 'ISS-2024-011',
        status: 'Pending',
        comment: 'Two street lights on Nadesar Palace Road not working. Very dark at night.',
        role: 'Citizen',
        attachments: ['https://images.pexels.com/photos/1112048/pexels-photo-1112048.jpeg'],
        updatedBy: 'citizen-11',
        scope: 'citizen',
        createdAt: '2024-02-26T08:00:00Z',
      },
      {
        id: 'upd-51',
        issueId: 'ISS-2024-011',
        status: 'Verified',
        comment: 'Verified on site. Two lamp posts confirmed faulty. MCB tripped in junction box.',
        role: 'UnitOfficer',
        attachments: [],
        updatedBy: 'uo-1',
        scope: 'field_and_citizen',
        createdAt: '2024-02-26T12:00:00Z',
      },
      {
        id: 'upd-52',
        issueId: 'ISS-2024-011',
        status: 'Assigned',
        comment: 'Priya Singh assigned. Electrical team dispatched with replacement parts.',
        role: 'UnitOfficer',
        attachments: [],
        updatedBy: 'uo-1',
        scope: 'admin_only',
        createdAt: '2024-02-26T14:00:00Z',
      },
      {
        id: 'upd-53',
        issueId: 'ISS-2024-011',
        status: 'In Progress',
        comment: 'Bulbs and MCB replaced in both lamp posts. Testing underway.',
        role: 'FieldOfficer',
        attachments: ['https://images.pexels.com/photos/1536988/pexels-photo-1536988.jpeg'],
        updatedBy: 'fo-2',
        scope: 'field_and_citizen',
        createdAt: '2024-02-27T10:00:00Z',
      },
      {
        id: 'upd-54',
        issueId: 'ISS-2024-011',
        status: 'Pending UO Verification',
        comment:
          'Both street lights repaired and fully operational. New LED bulbs installed. Area is well-lit.',
        role: 'FieldOfficer',
        attachments: [
          'https://images.pexels.com/photos/1536988/pexels-photo-1536988.jpeg',
          'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg',
        ],
        updatedBy: 'fo-2',
        scope: 'field_and_citizen',
        createdAt: '2024-02-27T17:30:00Z',
      },
    ],
    slaDeadline: '2026-04-22T23:59:59Z',
    coordinates: { latitude: 25.335, longitude: 82.965 },
    createdAt: '2024-02-26T08:00:00Z',
    images: ['https://images.pexels.com/photos/1112048/pexels-photo-1112048.jpeg'],
    foResolutionDescription:
      'Replaced faulty MCB and installed new 40W LED bulbs in both street lights on Nadesar Palace Road. Junction box cleaned and all electrical connections secured. Both lights are now fully functional and provide adequate lighting. Tested for 30 minutes before marking complete.',
    foBeforeLocation: { latitude: 25.327, longitude: 82.958, timestamp: '2024-02-27T08:15:00Z' },
    foAfterLocation: { latitude: 25.3268, longitude: 82.9578, timestamp: '2024-02-27T17:20:00Z' },
  },

  {
    id: 'ISS-2024-012',
    title: 'Collapsed Footpath - Kabir Chaura',
    description:
      'Footpath has caved in near Kabir Chaura market. Pedestrians forced onto the road, causing traffic hazards. Multiple complaints received over two months with no progress.',
    category: 'Road Repair',
    subCategories: ['Footpath Damage'],
    tags: ['#slaoverdue', '#footpath', '#kabirChaura', '#urgent', '#overdue'],
    priority: 'High',
    status: 'In Progress',
    location: 'Kabir Chaura Market Road',
    ward: 'Varanasi Zone',
    citizenName: 'Harish Agarwal',
    citizenEmail: 'harish.agarwal@gmail.com',
    citizenPhone: '+91 9876543221',
    dateReported: '2024-01-05T09:00:00Z',
    assignedOfficer: 'Rajesh Kumar',
    assignedOfficerId: 'fo-1',
    beforePhotos: [
      'https://images.pexels.com/photos/1670732/pexels-photo-1670732.jpeg',
      'https://images.pexels.com/photos/1563256/pexels-photo-1563256.jpeg',
    ],
    issueUpdates: [
      {
        id: 'upd-60',
        issueId: 'ISS-2024-012',
        status: 'Pending',
        comment: 'Footpath collapsed near Kabir Chaura market. Very dangerous for pedestrians.',
        role: 'Citizen',
        attachments: ['https://images.pexels.com/photos/1670732/pexels-photo-1670732.jpeg'],
        updatedBy: 'citizen-12',
        scope: 'citizen',
        createdAt: '2024-01-05T09:00:00Z',
      },
      {
        id: 'upd-61',
        issueId: 'ISS-2024-012',
        status: 'Verified',
        comment: 'Footpath damage confirmed on site. 25 metre stretch completely caved in.',
        role: 'UnitOfficer',
        attachments: [],
        updatedBy: 'uo-1',
        scope: 'field_and_citizen',
        createdAt: '2024-01-07T10:00:00Z',
      },
      {
        id: 'upd-62',
        issueId: 'ISS-2024-012',
        status: 'Assigned',
        comment: 'Rajesh Kumar assigned. Materials to be procured from municipal depot.',
        role: 'UnitOfficer',
        attachments: [],
        updatedBy: 'uo-1',
        scope: 'admin_only',
        createdAt: '2024-01-08T12:00:00Z',
      },
      {
        id: 'upd-63',
        issueId: 'ISS-2024-012',
        status: 'In Progress',
        comment: 'Excavation started. Awaiting cement delivery which is delayed from supplier.',
        role: 'FieldOfficer',
        attachments: [],
        updatedBy: 'fo-1',
        scope: 'field_and_citizen',
        createdAt: '2024-01-20T08:00:00Z',
      },
    ],
    slaDeadline: '2024-01-25T23:59:59Z',
    coordinates: { latitude: 25.319, longitude: 83.006 },
    createdAt: '2024-01-05T09:00:00Z',
    images: ['https://images.pexels.com/photos/1670732/pexels-photo-1670732.jpeg'],
  },

  {
    id: 'ISS-2024-013',
    title: 'Sewage Overflow - Orderly Bazar',
    description:
      'Raw sewage overflowing onto the main road near Orderly Bazar for over 6 weeks. Health emergency with severe stench and potential disease outbreak risk.',
    category: 'Drainage',
    subCategories: ['Drain Overflow', 'Blocked Drain'],
    tags: ['#slaoverdue', '#sewage', '#healthrisk', '#orderlybazar', '#critical'],
    priority: 'Critical',
    status: 'Assigned',
    location: 'Orderly Bazar, Main Crossing',
    ward: 'Varanasi Zone',
    citizenName: 'Shivam Chaturvedi',
    citizenEmail: 'shivam.chaturvedi@gmail.com',
    citizenPhone: '+91 9876543222',
    dateReported: '2023-12-10T07:30:00Z',
    assignedOfficer: 'Amit Verma',
    assignedOfficerId: 'fo-3',
    beforePhotos: ['https://images.pexels.com/photos/2768973/pexels-photo-2768973.jpeg'],
    issueUpdates: [
      {
        id: 'upd-64',
        issueId: 'ISS-2024-013',
        status: 'Pending',
        comment: 'Sewage overflowing for weeks. Children and elderly at high health risk.',
        role: 'Citizen',
        attachments: ['https://images.pexels.com/photos/2768973/pexels-photo-2768973.jpeg'],
        updatedBy: 'citizen-13',
        scope: 'citizen',
        createdAt: '2023-12-10T07:30:00Z',
      },
      {
        id: 'upd-65',
        issueId: 'ISS-2024-013',
        status: 'Verified',
        comment:
          'Massive overflow confirmed. Main sewer line choked. Health hazard classification: Severe.',
        role: 'UnitOfficer',
        attachments: [],
        updatedBy: 'uo-1',
        scope: 'field_and_citizen',
        createdAt: '2023-12-11T09:00:00Z',
      },
      {
        id: 'upd-66',
        issueId: 'ISS-2024-013',
        status: 'Assigned',
        comment:
          'Amit Verma assigned with full drainage team. Heavy desilting equipment requested.',
        role: 'UnitOfficer',
        attachments: [],
        updatedBy: 'uo-1',
        scope: 'field_and_citizen',
        createdAt: '2023-12-12T11:00:00Z',
      },
    ],
    slaDeadline: '2023-12-20T23:59:59Z',
    coordinates: { latitude: 25.305, longitude: 82.998 },
    createdAt: '2023-12-10T07:30:00Z',
    images: ['https://images.pexels.com/photos/2768973/pexels-photo-2768973.jpeg'],
  },

  {
    id: 'ISS-2024-014',
    title: 'Dangerous Loose Electrical Wires - Shivpur',
    description:
      'Exposed live wires hanging dangerously low at Shivpur junction. Risk of electrocution. A child was nearly injured last week. Repeated follow-ups ignored.',
    category: 'Street Light',
    subCategories: ['Damaged Pole'],
    tags: ['#slaoverdue', '#electricalhazard', '#shivpur', '#lifethreat', '#overdue'],
    priority: 'Critical',
    status: 'In Progress',
    location: 'Shivpur Junction, Near Petrol Pump',
    ward: 'Varanasi Zone',
    citizenName: 'Renu Srivastava',
    citizenEmail: 'renu.srivastava@gmail.com',
    citizenPhone: '+91 9876543223',
    dateReported: '2024-01-12T15:00:00Z',
    assignedOfficer: 'Manoj Kumar',
    assignedOfficerId: 'fo-9',
    beforePhotos: [
      'https://images.pexels.com/photos/1112048/pexels-photo-1112048.jpeg',
      'https://images.pexels.com/photos/280221/pexels-photo-280221.jpeg',
    ],
    issueUpdates: [
      {
        id: 'upd-67',
        issueId: 'ISS-2024-014',
        status: 'Pending',
        comment:
          'Loose wires hanging dangerously at Shivpur junction. Near electrocution incident yesterday.',
        role: 'Citizen',
        attachments: ['https://images.pexels.com/photos/1112048/pexels-photo-1112048.jpeg'],
        updatedBy: 'citizen-14',
        scope: 'citizen',
        createdAt: '2024-01-12T15:00:00Z',
      },
      {
        id: 'upd-68',
        issueId: 'ISS-2024-014',
        status: 'Verified',
        comment:
          'Three exposed 11KV wires confirmed hanging at 5 feet. Immediate danger. Barricaded area.',
        role: 'UnitOfficer',
        attachments: [],
        updatedBy: 'uo-1',
        scope: 'field_and_citizen',
        createdAt: '2024-01-13T08:00:00Z',
      },
      {
        id: 'upd-69',
        issueId: 'ISS-2024-014',
        status: 'Assigned',
        comment: 'Manoj Kumar assigned. UPPCL coordination required for high voltage line.',
        role: 'UnitOfficer',
        attachments: [],
        updatedBy: 'uo-1',
        scope: 'admin_only',
        createdAt: '2024-01-13T10:00:00Z',
      },
      {
        id: 'upd-70',
        issueId: 'ISS-2024-014',
        status: 'In Progress',
        comment:
          'UPPCL has been contacted. Waiting for their team to provide power shutdown clearance.',
        role: 'FieldOfficer',
        attachments: [],
        updatedBy: 'fo-9',
        scope: 'field_and_citizen',
        createdAt: '2024-01-18T10:00:00Z',
      },
    ],
    slaDeadline: '2024-01-20T23:59:59Z',
    coordinates: { latitude: 25.345, longitude: 82.94 },
    createdAt: '2024-01-12T15:00:00Z',
    images: ['https://images.pexels.com/photos/1112048/pexels-photo-1112048.jpeg'],
  },

  {
    id: 'ISS-2024-015',
    title: 'Water Pipeline Burst - Pahadia',
    description:
      'Major water pipeline burst near Pahadia crossing causing massive water loss and road damage. Issue was reported 45 days ago. No resolution yet despite 4 follow-ups.',
    category: 'Water Supply',
    subCategories: ['Water Leakage'],
    tags: ['#slaoverdue', '#pipelineburst', '#pahadia', '#waterloss', '#overdue'],
    priority: 'High',
    status: 'Rework Required',
    location: 'Pahadia Crossing, Ring Road',
    ward: 'Varanasi Zone',
    citizenName: 'Dhruv Mishra',
    citizenEmail: 'dhruv.mishra@gmail.com',
    citizenPhone: '+91 9876543224',
    dateReported: '2024-01-01T06:00:00Z',
    assignedOfficer: 'Deepak Gupta',
    assignedOfficerId: 'fo-7',
    beforePhotos: ['https://images.pexels.com/photos/4033111/pexels-photo-4033111.jpeg'],
    afterPhotos: ['https://images.pexels.com/photos/1416530/pexels-photo-1416530.jpeg'],
    issueUpdates: [
      {
        id: 'upd-71',
        issueId: 'ISS-2024-015',
        status: 'Pending',
        comment: 'Water gushing from broken pipeline since morning. Road is flooded.',
        role: 'Citizen',
        attachments: ['https://images.pexels.com/photos/4033111/pexels-photo-4033111.jpeg'],
        updatedBy: 'citizen-15',
        scope: 'citizen',
        createdAt: '2024-01-01T06:00:00Z',
      },
      {
        id: 'upd-72',
        issueId: 'ISS-2024-015',
        status: 'Verified',
        comment:
          '300mm diameter main pipeline rupture confirmed. Water loss estimated at 50,000 litres/hour.',
        role: 'UnitOfficer',
        attachments: [],
        updatedBy: 'uo-1',
        scope: 'field_and_citizen',
        createdAt: '2024-01-02T09:00:00Z',
      },
      {
        id: 'upd-73',
        issueId: 'ISS-2024-015',
        status: 'Assigned',
        comment: 'Deepak Gupta assigned with emergency pipeline repair team.',
        role: 'UnitOfficer',
        attachments: [],
        updatedBy: 'uo-1',
        scope: 'field_and_citizen',
        createdAt: '2024-01-02T12:00:00Z',
      },
      {
        id: 'upd-74',
        issueId: 'ISS-2024-015',
        status: 'In Progress',
        comment: 'Temporary patch applied. Main repair with new pipe section underway.',
        role: 'FieldOfficer',
        attachments: ['https://images.pexels.com/photos/1416530/pexels-photo-1416530.jpeg'],
        updatedBy: 'fo-7',
        scope: 'field_and_citizen',
        createdAt: '2024-01-05T08:00:00Z',
      },
      {
        id: 'upd-75',
        issueId: 'ISS-2024-015',
        status: 'Pending UO Verification',
        comment: 'Pipeline replaced and tested. No visible leak.',
        role: 'FieldOfficer',
        attachments: [],
        updatedBy: 'fo-7',
        scope: 'field_and_citizen',
        createdAt: '2024-01-08T16:00:00Z',
      },
      {
        id: 'upd-76',
        issueId: 'ISS-2024-015',
        status: 'Rework Required',
        comment:
          'Seepage found at new joint after 3 days. Pipe quality sub-standard. Complete redo required.',
        role: 'UnitOfficer',
        attachments: [],
        updatedBy: 'uo-1',
        scope: 'field_and_citizen',
        createdAt: '2024-01-12T11:00:00Z',
      },
    ],
    slaDeadline: '2024-01-10T23:59:59Z',
    coordinates: { latitude: 25.36, longitude: 82.975 },
    createdAt: '2024-01-01T06:00:00Z',
    images: ['https://images.pexels.com/photos/4033111/pexels-photo-4033111.jpeg'],
    reworkReason: 'Poor quality',
    reworkComment: 'Substandard pipe used. Complete section replacement required.',
  },

  {
    id: 'ISS-2024-016',
    title: 'Illegal Garbage Dumping - Pandeypur',
    description:
      'Large quantity of construction debris and household waste illegally dumped near Pandeypur park. Issue unresolved for 60 days. Vermin and mosquito breeding noticed.',
    category: 'Waste Management',
    subCategories: ['Illegal Dumping', 'Garbage Overflow'],
    tags: ['#slaoverdue', '#illegaldumping', '#pandeypur', '#vermin', '#overdue'],
    priority: 'Medium',
    status: 'Assigned',
    location: 'Pandeypur Park Road',
    ward: 'Varanasi Zone',
    citizenName: 'Sangeeta Pal',
    citizenEmail: 'sangeeta.pal@gmail.com',
    citizenPhone: '+91 9876543225',
    dateReported: '2023-11-20T11:00:00Z',
    assignedOfficer: 'Rekha Devi',
    assignedOfficerId: 'fo-8',
    beforePhotos: ['https://images.pexels.com/photos/128421/pexels-photo-128421.jpeg'],
    issueUpdates: [
      {
        id: 'upd-77',
        issueId: 'ISS-2024-016',
        status: 'Pending',
        comment: 'Construction waste dumped illegally near Pandeypur park. Smell is unbearable.',
        role: 'Citizen',
        attachments: ['https://images.pexels.com/photos/128421/pexels-photo-128421.jpeg'],
        updatedBy: 'citizen-16',
        scope: 'citizen',
        createdAt: '2023-11-20T11:00:00Z',
      },
      {
        id: 'upd-78',
        issueId: 'ISS-2024-016',
        status: 'Verified',
        comment: 'Verified. Over 3 tonnes of mixed debris. Health and civic violation confirmed.',
        role: 'UnitOfficer',
        attachments: [],
        updatedBy: 'uo-1',
        scope: 'field_and_citizen',
        createdAt: '2023-11-21T10:00:00Z',
      },
      {
        id: 'upd-79',
        issueId: 'ISS-2024-016',
        status: 'Assigned',
        comment: 'Rekha Devi assigned with sanitation vehicle for debris removal.',
        role: 'UnitOfficer',
        attachments: [],
        updatedBy: 'uo-1',
        scope: 'field_and_citizen',
        createdAt: '2023-11-22T09:00:00Z',
      },
    ],
    slaDeadline: '2023-12-01T23:59:59Z',
    coordinates: { latitude: 25.33, longitude: 82.95 },
    createdAt: '2023-11-20T11:00:00Z',
    images: ['https://images.pexels.com/photos/128421/pexels-photo-128421.jpeg'],
  },
];

export const mockDashboardStats: DashboardStats = {
  totalIssues: 10,
  pendingVerification: 1,
  verifiedReadyToAssign: 1,
  assigned: 1,
  submittedForReview: 1,
  reworkRequired: 1,
  reopened: 1,
  escalated: 1,
  closed: 2,
};

export const mockAnalyticsData: AnalyticsData = {
  slaCompliance: 78,
  avgVerificationTime: 4.2,
  avgResolutionTime: 48,
  categoryDistribution: [
    { category: 'Pothole', count: 2, percentage: 20 },
    { category: 'Street Light', count: 1, percentage: 10 },
    { category: 'Waste Management', count: 1, percentage: 10 },
    { category: 'Drainage', count: 2, percentage: 20 },
    { category: 'Road Repair', count: 1, percentage: 10 },
    { category: 'Water Supply', count: 1, percentage: 10 },
    { category: 'Park Maintenance', count: 1, percentage: 10 },
    { category: 'Public Safety', count: 1, percentage: 10 },
  ],
  escalationCount: 1,
  topPerformingOfficers: [
    { name: 'Priya Singh', successRate: 96, issuesResolved: 12 },
    { name: 'Sunita Yadav', successRate: 94, issuesResolved: 10 },
    { name: 'Rajesh Kumar', successRate: 92, issuesResolved: 15 },
  ],
};

export const mockMessages: Message[] = [
  {
    id: 'msg-1',
    issueId: 'ISS-2024-003',
    fromUserId: 'uo-1',
    fromUserName: 'Kumar Singh',
    fromRole: 'UnitOfficer',
    text: 'Please ensure all bins are cleared and area is cleaned properly.',
    timestamp: '2024-02-26T10:15:00Z',
    read: true,
  },
  {
    id: 'msg-2',
    issueId: 'ISS-2024-003',
    fromUserId: 'fo-4',
    fromUserName: 'Sunita Yadav',
    fromRole: 'FieldOfficer',
    text: 'Acknowledged. Will complete by evening today.',
    timestamp: '2024-02-26T10:30:00Z',
    read: true,
  },
  {
    id: 'msg-3',
    issueId: 'ISS-2024-005',
    fromUserId: 'fo-1',
    fromUserName: 'Rajesh Kumar',
    fromRole: 'FieldOfficer',
    text: 'Work completed. Please review the before and after photos.',
    timestamp: '2024-02-27T16:05:00Z',
    read: false,
  },
];

export const mockConversations: Conversation[] = [
  {
    issueId: 'ISS-2024-005',
    issueTitle: 'Road Repair Needed - Sigra',
    status: 'Pending UO Verification',
    lastMessage: 'Work completed. Please review the before and after photos.',
    lastMessageTime: '2024-02-27T16:05:00Z',
    unreadCount: 1,
  },
  {
    issueId: 'ISS-2024-003',
    issueTitle: 'Overflowing Garbage Bins - Dashashwamedh',
    status: 'Assigned',
    lastMessage: 'Acknowledged. Will complete by evening today.',
    lastMessageTime: '2024-02-26T10:30:00Z',
    unreadCount: 0,
  },
];

export const CURRENT_USER_ID = 'uo-varanasi-1';

export const mockOfficials: OfficialUser[] = [
  {
    id: 'uo-varanasi-1',
    name: 'Anand Tripathi',
    role: 'UnitOfficer',
    designation: 'Unit Officer',
    department: 'Municipal Corporation Varanasi',
    ward: 'Varanasi Zone',
    avatar: 'https://i.pravatar.cc/150?img=68',
    isOnline: true,
  },
  {
    id: 'fo-1',
    name: 'Rajesh Kumar',
    role: 'FieldOfficer',
    designation: 'Field Officer',
    department: 'Roads & Infrastructure',
    ward: 'Varanasi Zone',
    avatar: 'https://i.pravatar.cc/150?img=12',
    isOnline: true,
    lastSeen: '2024-02-28T10:30:00Z',
  },
  {
    id: 'fo-2',
    name: 'Priya Singh',
    role: 'FieldOfficer',
    designation: 'Field Officer',
    department: 'Electrical & Street Lighting',
    ward: 'Varanasi Zone',
    avatar: 'https://i.pravatar.cc/150?img=47',
    isOnline: false,
    lastSeen: '2024-02-28T11:15:00Z',
  },
  {
    id: 'fo-3',
    name: 'Amit Verma',
    role: 'FieldOfficer',
    designation: 'Field Officer',
    department: 'Drainage & Water Supply',
    ward: 'Varanasi Zone',
    avatar: 'https://i.pravatar.cc/150?img=33',
    isOnline: true,
    lastSeen: '2024-02-28T09:45:00Z',
  },
  {
    id: 'fo-4',
    name: 'Sunita Yadav',
    role: 'FieldOfficer',
    designation: 'Field Officer',
    department: 'Sanitation & Parks',
    ward: 'Varanasi Zone',
    avatar: 'https://i.pravatar.cc/150?img=44',
    isOnline: false,
    lastSeen: '2024-02-28T10:00:00Z',
  },
  {
    id: 'fo-5',
    name: 'Vikram Mishra',
    role: 'FieldOfficer',
    designation: 'Field Officer',
    department: 'Roads & Drainage',
    ward: 'Varanasi Zone',
    avatar: 'https://i.pravatar.cc/150?img=15',
    isOnline: false,
    lastSeen: '2024-02-28T08:30:00Z',
  },
  {
    id: 'fo-7',
    name: 'Deepak Gupta',
    role: 'FieldOfficer',
    designation: 'Field Officer',
    department: 'Roads & Infrastructure',
    ward: 'Varanasi Zone',
    avatar: 'https://i.pravatar.cc/150?img=51',
    isOnline: true,
    lastSeen: '2024-02-28T09:00:00Z',
  },
  {
    id: 'fo-9',
    name: 'Manoj Kumar',
    role: 'FieldOfficer',
    designation: 'Field Officer',
    department: 'Electrical & Public Safety',
    ward: 'Varanasi Zone',
    avatar: 'https://i.pravatar.cc/150?img=60',
    isOnline: false,
    lastSeen: '2024-02-28T08:00:00Z',
  },
  {
    id: 'admin-1',
    name: 'D.K. Sharma',
    role: 'Admin',
    designation: 'Deputy Commissioner',
    department: 'Varanasi Nagar Nigam',
    avatar: 'https://i.pravatar.cc/150?img=57',
    isOnline: false,
    lastSeen: '2024-02-27T18:00:00Z',
  },
  {
    id: 'ca-1',
    name: 'Smt. Rekha Agarwal',
    role: 'CityAdmin',
    designation: 'City Administrator',
    department: 'Smart City Varanasi',
    avatar: 'https://i.pravatar.cc/150?img=49',
    isOnline: true,
    lastSeen: '2024-02-28T11:00:00Z',
  },
];

export const mockDirectMessages: DirectMessage[] = [
  {
    id: 'dm-1',
    conversationId: 'conv-1',
    fromUserId: 'uo-varanasi-1',
    fromUserName: 'Anand Tripathi',
    fromRole: 'UnitOfficer',
    text: 'Rajesh, the Sigra road repair has been pending for a while. Please ensure the before photos are geo-tagged properly before submission.',
    timestamp: '2024-02-27T09:00:00Z',
    read: true,
  },
  {
    id: 'dm-2',
    conversationId: 'conv-1',
    fromUserId: 'fo-1',
    fromUserName: 'Rajesh Kumar',
    fromRole: 'FieldOfficer',
    text: 'Sir, understood. I have started the resurfacing today. Photos are being geotagged. Will submit by evening.',
    timestamp: '2024-02-27T09:30:00Z',
    read: true,
    issueRef: { issueId: 'ISS-2024-005', issueTitle: 'Road Repair Needed - Sigra' },
  },
  {
    id: 'dm-3',
    conversationId: 'conv-1',
    fromUserId: 'uo-varanasi-1',
    fromUserName: 'Anand Tripathi',
    fromRole: 'UnitOfficer',
    text: 'Good. Also make sure the road marking re-painting is done properly. Last time it faded within a week.',
    timestamp: '2024-02-27T09:45:00Z',
    read: true,
  },
  {
    id: 'dm-4',
    conversationId: 'conv-1',
    fromUserId: 'fo-1',
    fromUserName: 'Rajesh Kumar',
    fromRole: 'FieldOfficer',
    text: 'Sir, work completed. Uploaded all resolution photos and location data. Please review when you get a chance. Used premium bitumen VG-30 this time.',
    timestamp: '2024-02-27T16:05:00Z',
    read: false,
    issueRef: { issueId: 'ISS-2024-005', issueTitle: 'Road Repair Needed - Sigra' },
  },

  {
    id: 'dm-5',
    conversationId: 'conv-2',
    fromUserId: 'fo-3',
    fromUserName: 'Amit Verma',
    fromRole: 'FieldOfficer',
    text: 'Sir, regarding ISS-2024-006 — I replaced the joint and sealed it as per standard procedure. The initial seepage was due to pressure spike at night. I will do a pressure test tomorrow morning.',
    timestamp: '2024-02-26T12:00:00Z',
    read: true,
    issueRef: { issueId: 'ISS-2024-006', issueTitle: 'Water Leak - Sunderpur' },
  },
  {
    id: 'dm-6',
    conversationId: 'conv-2',
    fromUserId: 'uo-varanasi-1',
    fromUserName: 'Anand Tripathi',
    fromRole: 'UnitOfficer',
    text: 'Amit, the leak is still showing. I visited the site personally. The pipe material used is sub-standard. I am marking this as Rework Required. Please source proper ISI-certified pipes.',
    timestamp: '2024-02-26T14:30:00Z',
    read: true,
  },
  {
    id: 'dm-7',
    conversationId: 'conv-2',
    fromUserId: 'fo-3',
    fromUserName: 'Amit Verma',
    fromRole: 'FieldOfficer',
    text: 'Understood, sir. I apologise for the oversight. Will arrange ISI-certified Class C pipes from the municipal store. Can you approve the material requisition form?',
    timestamp: '2024-02-26T15:00:00Z',
    read: true,
  },
  {
    id: 'dm-8',
    conversationId: 'conv-2',
    fromUserId: 'uo-varanasi-1',
    fromUserName: 'Anand Tripathi',
    fromRole: 'UnitOfficer',
    text: 'Approved. Please complete the rework within 48 hours. The SLA is already breached.',
    timestamp: '2024-02-26T15:30:00Z',
    read: false,
  },

  {
    id: 'dm-9',
    conversationId: 'conv-3',
    fromUserId: 'fo-4',
    fromUserName: 'Sunita Yadav',
    fromRole: 'FieldOfficer',
    text: 'Sir, I have cleared all 4 bins at Dashashwamedh Ghat. Area sanitised. But I noticed the bins themselves are broken — lids missing on 2 of them. Should I raise a separate request?',
    timestamp: '2024-02-26T18:00:00Z',
    read: true,
    issueRef: { issueId: 'ISS-2024-003', issueTitle: 'Overflowing Garbage Bins - Dashashwamedh' },
  },
  {
    id: 'dm-10',
    conversationId: 'conv-3',
    fromUserId: 'uo-varanasi-1',
    fromUserName: 'Anand Tripathi',
    fromRole: 'UnitOfficer',
    text: 'Good work Sunita. Yes, please raise a separate issue for the bin replacements. Tag it under Waste Management category.',
    timestamp: '2024-02-26T18:30:00Z',
    read: true,
  },
  {
    id: 'dm-11',
    conversationId: 'conv-3',
    fromUserId: 'fo-4',
    fromUserName: 'Sunita Yadav',
    fromRole: 'FieldOfficer',
    text: 'Done, sir. New issue raised. Also the Pandeypur illegal dumping site (ISS-2024-016) — the debris quantity is more than estimated. May need a second vehicle tomorrow.',
    timestamp: '2024-02-27T08:00:00Z',
    read: false,
    issueRef: { issueId: 'ISS-2024-016', issueTitle: 'Illegal Garbage Dumping - Pandeypur' },
  },

  {
    id: 'dm-12',
    conversationId: 'conv-4',
    fromUserId: 'admin-1',
    fromUserName: 'D.K. Sharma',
    fromRole: 'Admin',
    text: 'Anand, I have reviewed the SLA overdue report. ISS-2024-012 (Kabir Chaura footpath) and ISS-2024-013 (Orderly Bazar sewage) need immediate attention. Please escalate if not resolved by this week.',
    timestamp: '2024-02-27T10:00:00Z',
    read: true,
  },
  {
    id: 'dm-13',
    conversationId: 'conv-4',
    fromUserId: 'uo-varanasi-1',
    fromUserName: 'Anand Tripathi',
    fromRole: 'UnitOfficer',
    text: 'Sir, noted. For ISS-2024-013 (sewage overflow), the desilting machine broke down last week. I have escalated for heavy equipment from the regional depot. Expecting delivery Thursday.',
    timestamp: '2024-02-27T10:30:00Z',
    read: true,
  },
  {
    id: 'dm-14',
    conversationId: 'conv-4',
    fromUserId: 'admin-1',
    fromUserName: 'D.K. Sharma',
    fromRole: 'Admin',
    text: 'Understood. Keep me posted daily on both issues. Also the ISS-2024-008 traffic safety escalation — has police coordination been initiated?',
    timestamp: '2024-02-27T11:00:00Z',
    read: false,
  },

  {
    id: 'dm-15',
    conversationId: 'conv-5',
    fromUserId: 'fo-2',
    fromUserName: 'Priya Singh',
    fromRole: 'FieldOfficer',
    text: 'Sir, the Nadesar street light repair is complete. Both lamps fully operational with new LED bulbs. After-photos uploaded. Please verify at your convenience.',
    timestamp: '2024-02-27T17:30:00Z',
    read: true,
    issueRef: { issueId: 'ISS-2024-011', issueTitle: 'Broken Street Light - Nadesar' },
  },
  {
    id: 'dm-16',
    conversationId: 'conv-5',
    fromUserId: 'uo-varanasi-1',
    fromUserName: 'Anand Tripathi',
    fromRole: 'UnitOfficer',
    text: 'Great work Priya. I will do the site verification tomorrow morning. If all looks good, I will close it immediately. Also — Bhelupur traffic issue, any update from the traffic department?',
    timestamp: '2024-02-27T18:00:00Z',
    read: true,
  },
  {
    id: 'dm-17',
    conversationId: 'conv-5',
    fromUserId: 'fo-2',
    fromUserName: 'Priya Singh',
    fromRole: 'FieldOfficer',
    text: 'Sir, the ACP Bhelupur has verbally agreed but waiting for the written NOC. I expect to receive it by tomorrow. Will share immediately.',
    timestamp: '2024-02-27T18:15:00Z',
    read: false,
    issueRef: { issueId: 'ISS-2024-008', issueTitle: 'Traffic Safety Issue - Bhelupur' },
  },

  {
    id: 'dm-18',
    conversationId: 'conv-6',
    fromUserId: 'fo-7',
    fromUserName: 'Deepak Gupta',
    fromRole: 'FieldOfficer',
    text: 'Sir, the Pahadia pipeline (ISS-2024-015) rework is underway. ISI-certified pipe section arrived. Excavation starts at 8am tomorrow.',
    timestamp: '2024-02-27T20:00:00Z',
    read: true,
    issueRef: { issueId: 'ISS-2024-015', issueTitle: 'Water Pipeline Burst - Pahadia' },
  },
  {
    id: 'dm-19',
    conversationId: 'conv-6',
    fromUserId: 'uo-varanasi-1',
    fromUserName: 'Anand Tripathi',
    fromRole: 'UnitOfficer',
    text: 'Good, Deepak. Ensure the welding joint is done by a certified plumber this time. I will be on site for inspection at 11am.',
    timestamp: '2024-02-27T20:30:00Z',
    read: false,
  },
];

export const mockDirectConversations: DirectConversation[] = [
  {
    id: 'conv-1',
    participantIds: ['uo-varanasi-1', 'fo-1'],
    participants: [],
    lastMessage:
      'Sir, work completed. Uploaded all resolution photos and location data. Please review when you get a chance.',
    lastMessageTime: '2024-02-27T16:05:00Z',
    lastMessageSenderId: 'fo-1',
    unreadCount: 1,
    issueRef: {
      issueId: 'ISS-2024-005',
      issueTitle: 'Road Repair Needed - Sigra',
      status: 'Pending UO Verification',
    },
  },
  {
    id: 'conv-4',
    participantIds: ['uo-varanasi-1', 'admin-1'],
    participants: [],
    lastMessage: 'Understood. Keep me posted daily on both issues.',
    lastMessageTime: '2024-02-27T11:00:00Z',
    lastMessageSenderId: 'admin-1',
    unreadCount: 1,
  },
  {
    id: 'conv-5',
    participantIds: ['uo-varanasi-1', 'fo-2'],
    participants: [],
    lastMessage:
      'Sir, the ACP has verbally agreed but waiting for written NOC. Will share immediately.',
    lastMessageTime: '2024-02-27T18:15:00Z',
    lastMessageSenderId: 'fo-2',
    unreadCount: 1,
    issueRef: {
      issueId: 'ISS-2024-011',
      issueTitle: 'Broken Street Light - Nadesar',
      status: 'Pending UO Verification',
    },
  },
  {
    id: 'conv-2',
    participantIds: ['uo-varanasi-1', 'fo-3'],
    participants: [],
    lastMessage:
      'Approved. Please complete the rework within 48 hours. The SLA is already breached.',
    lastMessageTime: '2024-02-26T15:30:00Z',
    lastMessageSenderId: 'uo-varanasi-1',
    unreadCount: 0,
    issueRef: {
      issueId: 'ISS-2024-006',
      issueTitle: 'Water Leak - Sunderpur',
      status: 'Rework Required',
    },
  },
  {
    id: 'conv-3',
    participantIds: ['uo-varanasi-1', 'fo-4'],
    participants: [],
    lastMessage:
      'Done, sir. New issue raised. The debris quantity is more than estimated — may need a second vehicle.',
    lastMessageTime: '2024-02-27T08:00:00Z',
    lastMessageSenderId: 'fo-4',
    unreadCount: 1,
    issueRef: {
      issueId: 'ISS-2024-003',
      issueTitle: 'Overflowing Garbage Bins - Dashashwamedh',
      status: 'Assigned',
    },
  },
  {
    id: 'conv-6',
    participantIds: ['uo-varanasi-1', 'fo-7'],
    participants: [],
    lastMessage: 'Good. Ensure the welding joint is done by a certified plumber this time.',
    lastMessageTime: '2024-02-27T20:30:00Z',
    lastMessageSenderId: 'uo-varanasi-1',
    unreadCount: 0,
    issueRef: {
      issueId: 'ISS-2024-015',
      issueTitle: 'Water Pipeline Burst - Pahadia',
      status: 'Rework Required',
    },
  },
];

export const mockUnitOfficerNotifications: AppNotification[] = [
  {
    id: 'notif-uo-1',
    userId: 'uo-varanasi-1',
    userRole: 'UnitOfficer',
    type: 'verification',
    title: 'Issue Pending Verification',
    message:
      'ISS-2024-011 (Broken Street Light - Nadesar) has been submitted by Priya Singh and is awaiting your verification. After-photos have been uploaded.',
    read: false,
    createdAt: '2024-02-27T17:35:00Z',
    issueId: 'ISS-2024-011',
  },
  {
    id: 'notif-uo-2',
    userId: 'uo-varanasi-1',
    userRole: 'UnitOfficer',
    type: 'verification',
    title: 'Issue Ready for Review',
    message:
      'ISS-2024-005 (Road Repair Needed - Sigra) has been marked complete by Rajesh Kumar. Resolution photos and geo-tags have been submitted for your approval.',
    read: false,
    createdAt: '2024-02-27T16:10:00Z',
    issueId: 'ISS-2024-005',
  },
  {
    id: 'notif-uo-3',
    userId: 'uo-varanasi-1',
    userRole: 'UnitOfficer',
    type: 'sla_alert',
    title: 'SLA Overdue — Critical Issue',
    message:
      'ISS-2024-013 (Sewage Overflow - Orderly Bazar) is 69 days overdue. The SLA deadline was 20 Dec 2023. Immediate escalation is recommended.',
    read: false,
    createdAt: '2024-02-27T09:00:00Z',
    issueId: 'ISS-2024-013',
  },
  {
    id: 'notif-uo-4',
    userId: 'uo-varanasi-1',
    userRole: 'UnitOfficer',
    type: 'sla_alert',
    title: 'SLA Overdue — High Priority',
    message:
      'ISS-2024-012 (Collapsed Footpath - Kabir Chaura) is 33 days overdue. The assigned officer Rajesh Kumar has reported a cement supply delay. Please review and take action.',
    read: false,
    createdAt: '2024-02-27T09:05:00Z',
    issueId: 'ISS-2024-012',
  },
  {
    id: 'notif-uo-5',
    userId: 'uo-varanasi-1',
    userRole: 'UnitOfficer',
    type: 'escalation',
    title: 'Issue Escalated to Admin',
    message:
      'ISS-2024-008 (Traffic Safety Issue - Bhelupur) has been escalated to Administration (D.K. Sharma) due to SLA breach. Police coordination pending. You will be notified once the Admin responds.',
    read: true,
    createdAt: '2024-02-25T10:05:00Z',
    issueId: 'ISS-2024-008',
  },
  {
    id: 'notif-uo-6',
    userId: 'uo-varanasi-1',
    userRole: 'UnitOfficer',
    type: 'reopened',
    title: 'Issue Reopened by Citizen',
    message:
      'ISS-2024-007 (Park Maintenance - Ravidas Park) has been reopened by the citizen Kavita Singh. Reason: Two benches near the east gate were not replaced as promised. Please reassign or investigate.',
    read: true,
    createdAt: '2024-02-26T14:05:00Z',
    issueId: 'ISS-2024-007',
  },
  {
    id: 'notif-uo-7',
    userId: 'uo-varanasi-1',
    userRole: 'UnitOfficer',
    type: 'rework',
    title: 'Rework Required — Water Leak',
    message:
      'ISS-2024-006 (Water Leak - Sunderpur) rework was marked required after your site visit. Amit Verma has acknowledged and requested approval for ISI-certified pipe materials.',
    read: true,
    createdAt: '2024-02-26T15:35:00Z',
    issueId: 'ISS-2024-006',
  },
  {
    id: 'notif-uo-8',
    userId: 'uo-varanasi-1',
    userRole: 'UnitOfficer',
    type: 'message',
    title: 'New Message from D.K. Sharma',
    message:
      'Deputy Commissioner D.K. Sharma has sent you a message regarding SLA overdue issues. Please review: "Keep me posted daily on ISS-2024-012 and ISS-2024-013. Has police coordination been initiated for ISS-2024-008?"',
    read: true,
    createdAt: '2024-02-27T11:02:00Z',
  },
  {
    id: 'notif-uo-9',
    userId: 'uo-varanasi-1',
    userRole: 'UnitOfficer',
    type: 'system',
    title: 'Monthly SLA Report Available',
    message:
      'The February 2024 SLA compliance report is now available. Your zone achieved 78% compliance this month. 2 issues remain critically overdue. Download the full report from the Analytics tab.',
    read: true,
    createdAt: '2024-02-28T08:00:00Z',
  },
];

export const mockFieldOfficerNotifications: AppNotification[] = [
  {
    id: 'notif-fo-1',
    userId: 'fo-1',
    userRole: 'FieldOfficer',
    type: 'assignment',
    title: 'New Issue Assigned',
    message:
      'ISS-2024-012 (Collapsed Footpath - Kabir Chaura) has been assigned to you by Unit Officer Anand Tripathi. Priority: High. SLA deadline was 25 Jan 2024 — this is overdue. Please take immediate action.',
    read: false,
    createdAt: '2024-01-08T12:05:00Z',
    issueId: 'ISS-2024-012',
  },
  {
    id: 'notif-fo-2',
    userId: 'fo-1',
    userRole: 'FieldOfficer',
    type: 'sla_alert',
    title: 'SLA Deadline Breached',
    message:
      'ISS-2024-012 (Collapsed Footpath - Kabir Chaura) has breached its SLA deadline of 25 Jan 2024. The issue is still In Progress. Please update the status and provide a timeline for completion.',
    read: false,
    createdAt: '2024-01-26T09:00:00Z',
    issueId: 'ISS-2024-012',
  },
  {
    id: 'notif-fo-3',
    userId: 'fo-1',
    userRole: 'FieldOfficer',
    type: 'message',
    title: 'Message from Unit Officer',
    message:
      'Anand Tripathi (Unit Officer) sent a message: "Rajesh, ensure the road marking re-painting is done properly this time. Last time it faded within a week." Regarding ISS-2024-005 (Road Repair - Sigra).',
    read: false,
    createdAt: '2024-02-27T09:46:00Z',
    issueId: 'ISS-2024-005',
  },
  {
    id: 'notif-fo-4',
    userId: 'fo-1',
    userRole: 'FieldOfficer',
    type: 'verification',
    title: 'Work Submission Received',
    message:
      'Your work submission for ISS-2024-005 (Road Repair - Sigra) has been received by Unit Officer Anand Tripathi. Verification is in progress. You will be notified once it is approved or rework is requested.',
    read: true,
    createdAt: '2024-02-27T16:20:00Z',
    issueId: 'ISS-2024-005',
  },
  {
    id: 'notif-fo-5',
    userId: 'fo-2',
    userRole: 'FieldOfficer',
    type: 'assignment',
    title: 'New Issue Assigned',
    message:
      'ISS-2024-011 (Broken Street Light - Nadesar) has been assigned to you by Unit Officer Anand Tripathi. Priority: High. Please inspect and complete repair with LED replacements. SLA: 22 Apr 2026.',
    read: false,
    createdAt: '2024-02-26T14:05:00Z',
    issueId: 'ISS-2024-011',
  },
  {
    id: 'notif-fo-6',
    userId: 'fo-2',
    userRole: 'FieldOfficer',
    type: 'message',
    title: 'Message from Unit Officer',
    message:
      'Anand Tripathi: "Great work Priya. I will do the site verification tomorrow morning. Also — Bhelupur traffic issue, any update from the traffic department?" Regarding ISS-2024-011 and ISS-2024-008.',
    read: false,
    createdAt: '2024-02-27T18:02:00Z',
    issueId: 'ISS-2024-011',
  },
  {
    id: 'notif-fo-7',
    userId: 'fo-3',
    userRole: 'FieldOfficer',
    type: 'rework',
    title: 'Rework Required',
    message:
      'ISS-2024-006 (Water Leak - Sunderpur) has been marked as Rework Required by Unit Officer Anand Tripathi. Reason: Substandard pipe material used. Please source ISI-certified Class C pipes and redo the repair within 48 hours.',
    read: false,
    createdAt: '2024-02-26T14:35:00Z',
    issueId: 'ISS-2024-006',
  },
  {
    id: 'notif-fo-8',
    userId: 'fo-3',
    userRole: 'FieldOfficer',
    type: 'assignment',
    title: 'Issue Assigned',
    message:
      'ISS-2024-013 (Sewage Overflow - Orderly Bazar) has been assigned to you. This is a Critical priority issue marked as SLA overdue. Heavy desilting equipment has been requested from the regional depot.',
    read: true,
    createdAt: '2023-12-12T11:05:00Z',
    issueId: 'ISS-2024-013',
  },
  {
    id: 'notif-fo-9',
    userId: 'fo-4',
    userRole: 'FieldOfficer',
    type: 'assignment',
    title: 'New Issue Assigned',
    message:
      'ISS-2024-003 (Overflowing Garbage Bins - Dashashwamedh) has been assigned to you by Unit Officer Anand Tripathi. Priority: High. Please complete clearance today. SLA: 10 Apr 2026.',
    read: true,
    createdAt: '2024-02-26T10:02:00Z',
    issueId: 'ISS-2024-003',
  },
  {
    id: 'notif-fo-10',
    userId: 'fo-4',
    userRole: 'FieldOfficer',
    type: 'system',
    title: 'New Issue Alert in Your Area',
    message:
      'A new High-priority issue has been reported near Pandeypur (ISS-2024-016 - Illegal Garbage Dumping). It has been assigned to you along with a sanitation vehicle for debris removal.',
    read: true,
    createdAt: '2023-11-22T09:05:00Z',
    issueId: 'ISS-2024-016',
  },
];

export const mockCitizenMessages: CitizenMessage[] = [
  {
    id: 'cm-1',
    issueId: 'ISS-2024-001',
    fromId: 'citizen-ramesh',
    fromName: 'Ramesh Gupta',
    fromRole: 'Citizen',
    fromAvatar: 'https://i.pravatar.cc/100?img=56',
    text: 'Hello, I reported this pothole 3 days ago. When will it be fixed? The road is dangerous for two-wheelers.',
    timestamp: '2026-03-12T09:15:00Z',
    read: true,
  },
  {
    id: 'cm-2',
    issueId: 'ISS-2024-001',
    fromId: 'fo-1',
    fromName: 'Rajesh Kumar',
    fromRole: 'FieldOfficer',
    fromAvatar: 'https://i.pravatar.cc/150?img=12',
    text: 'Namaste Ramesh Ji, we have received your complaint. Our team will be on-site tomorrow between 10 AM and 12 PM to assess and begin repairs.',
    timestamp: '2026-03-12T10:30:00Z',
    read: true,
  },
  {
    id: 'cm-3',
    issueId: 'ISS-2024-001',
    fromId: 'citizen-ramesh',
    fromName: 'Ramesh Gupta',
    fromRole: 'Citizen',
    fromAvatar: 'https://i.pravatar.cc/100?img=56',
    text: 'Thank you! Please also check the smaller pothole just 20 meters ahead near the bus stop. That one is also causing issues.',
    timestamp: '2026-03-12T11:05:00Z',
    read: true,
  },
  {
    id: 'cm-4',
    issueId: 'ISS-2024-001',
    fromId: 'fo-1',
    fromName: 'Rajesh Kumar',
    fromRole: 'FieldOfficer',
    fromAvatar: 'https://i.pravatar.cc/150?img=12',
    text: 'Yes, we have noted that as well. Both potholes will be addressed in the same visit. We will need to close one lane temporarily. Please inform your neighbours.',
    timestamp: '2026-03-12T11:40:00Z',
    read: true,
  },
  {
    id: 'cm-5',
    issueId: 'ISS-2024-001',
    fromId: 'citizen-ramesh',
    fromName: 'Ramesh Gupta',
    fromRole: 'Citizen',
    fromAvatar: 'https://i.pravatar.cc/100?img=56',
    text: 'Okay understood. Will the work be completed in one day or will it take longer?',
    timestamp: '2026-03-13T08:20:00Z',
    read: true,
  },
  {
    id: 'cm-6',
    issueId: 'ISS-2024-001',
    fromId: 'fo-1',
    fromName: 'Rajesh Kumar',
    fromRole: 'FieldOfficer',
    fromAvatar: 'https://i.pravatar.cc/150?img=12',
    text: 'We expect to finish by evening today. The crew has arrived at the site and work has started. You can see the progress in real time.',
    timestamp: '2026-03-13T10:55:00Z',
    read: true,
  },
  {
    id: 'cm-7',
    issueId: 'ISS-2024-001',
    fromId: 'citizen-ramesh',
    fromName: 'Ramesh Gupta',
    fromRole: 'Citizen',
    fromAvatar: 'https://i.pravatar.cc/100?img=56',
    text: 'I can see the crew from my window. Great work! Thank you for the quick response. Very happy with the CityCare service.',
    timestamp: '2026-03-13T14:30:00Z',
    read: false,
  },
  {
    id: 'cm-8',
    issueId: 'ISS-2024-001',
    fromId: 'citizen-ramesh',
    fromName: 'Ramesh Gupta',
    fromRole: 'Citizen',
    fromAvatar: 'https://i.pravatar.cc/100?img=56',
    text: 'The road looks much better now. Please also arrange for road markings to be repainted in this area.',
    timestamp: '2026-03-14T09:10:00Z',
    read: false,
  },
  {
    id: 'cm-9',
    issueId: 'ISS-2024-002',
    fromId: 'citizen-kavita',
    fromName: 'Kavita Sharma',
    fromRole: 'Citizen',
    fromAvatar: 'https://i.pravatar.cc/100?img=47',
    text: 'The streetlight at the crossing near Assi Ghat has been out for a week. It is very unsafe at night. Please fix it urgently.',
    timestamp: '2026-03-11T20:00:00Z',
    read: true,
  },
  {
    id: 'cm-10',
    issueId: 'ISS-2024-002',
    fromId: 'fo-2',
    fromName: 'Priya Singh',
    fromRole: 'FieldOfficer',
    fromAvatar: 'https://i.pravatar.cc/150?img=47',
    text: 'We acknowledge your complaint. A technician will inspect the light tomorrow. We will update you shortly.',
    timestamp: '2026-03-11T21:30:00Z',
    read: true,
  },
  {
    id: 'cm-11',
    issueId: 'ISS-2024-002',
    fromId: 'citizen-kavita',
    fromName: 'Kavita Sharma',
    fromRole: 'Citizen',
    fromAvatar: 'https://i.pravatar.cc/100?img=47',
    text: 'Thank you. Please also check the adjacent pole which is leaning dangerously.',
    timestamp: '2026-03-12T07:45:00Z',
    read: false,
  },
];

export const publicIssues: PublicIssue[] = [
  {
    id: 'PUB-001',
    original_issue_id: 'ISS-2024-001',
    title: 'Pothole Repair Completed on Assi Ghat Road',
    category: 'Pothole',
    ward: 'Ward 04 - Assi Ghat',
    location: 'Assi Ghat Road, Near Temple Gate',
    status: 'Resolved',
    summary:
      'A large pothole near the main temple gate on Assi Ghat Road has been successfully repaired. The road surface has been restored to a safe condition using cold-mix asphalt. Surrounding areas were also levelled to prevent waterlogging.',
    before_images: [
      'https://images.pexels.com/photos/6146961/pexels-photo-6146961.jpeg',
      'https://images.pexels.com/photos/1461974/pexels-photo-1461974.jpeg',
    ],
    after_images: ['https://images.pexels.com/photos/1105766/pexels-photo-1105766.jpeg'],
    resolved_by: 'Field Officer Team — Road Maintenance Unit',
    resolved_date: '2026-03-10',
    moderated_by: 'Unit Officer Rajesh',
    moderated_at: '2026-03-11T09:00:00Z',
    public_visible: true,
    publish_status: 'published',
    view_count: 214,
  },
  {
    id: 'PUB-002',
    original_issue_id: 'ISS-2024-007',
    title: 'Park Maintenance Completed — Ravidas Park, Khojwa',
    category: 'Park Maintenance',
    ward: 'Ward 09 - Khojwa',
    location: 'Ravidas Park, Khojwa Area',
    status: 'Resolved',
    summary:
      'Extensive maintenance work completed at Ravidas Park. Six broken benches replaced, damaged walkway repaired across three sections, and overgrown branches trimmed. The park has been restored for safe public use.',
    before_images: [
      'https://images.pexels.com/photos/1301856/pexels-photo-1301856.jpeg',
      'https://images.pexels.com/photos/1179229/pexels-photo-1179229.jpeg',
    ],
    after_images: ['https://images.pexels.com/photos/1105766/pexels-photo-1105766.jpeg'],
    resolved_by: 'Field Officer Sunita Yadav — Parks & Maintenance Division',
    resolved_date: '2026-03-12',
    moderated_by: 'Unit Officer Rajesh',
    moderated_at: '2026-03-13T11:30:00Z',
    public_visible: true,
    publish_status: 'published',
    view_count: 98,
  },
  {
    id: 'PUB-003',
    original_issue_id: 'ISS-2024-004',
    title: 'Drainage Blockage Cleared — Lanka Chowk',
    category: 'Drainage',
    ward: 'Ward 06 - Lanka',
    location: 'Lanka Chowk, Near University Gate',
    status: 'Resolved',
    summary:
      'Severe drainage blockage near Lanka Chowk university gate has been fully cleared. Municipal drainage team removed accumulated debris and silt. Anti-blockage mesh installed to prevent recurrence.',
    before_images: ['https://images.pexels.com/photos/1462011/pexels-photo-1462011.jpeg'],
    after_images: ['https://images.pexels.com/photos/1367276/pexels-photo-1367276.jpeg'],
    resolved_by: 'Field Officer Amit Verma — Drainage & Water Unit',
    resolved_date: '2026-03-08',
    moderated_by: 'Unit Officer Rajesh',
    moderated_at: '2026-03-09T14:00:00Z',
    public_visible: true,
    publish_status: 'published',
    view_count: 156,
  },
  {
    id: 'PUB-004',
    original_issue_id: 'ISS-2024-002',
    title: 'Street Light Restored — Godowlia Crossing',
    category: 'Street Light',
    ward: 'Ward 02 - Godowlia',
    location: 'Godowlia Crossing, Main Road',
    status: 'Resolved',
    summary:
      'Non-functional street light at Godowlia Crossing has been repaired. Damaged ballast unit replaced and wiring inspected. Light is now fully operational, improving nighttime safety in the area.',
    before_images: ['https://images.pexels.com/photos/1181824/pexels-photo-1181824.jpeg'],
    after_images: ['https://images.pexels.com/photos/1105766/pexels-photo-1105766.jpeg'],
    resolved_by: 'Field Officer Priya Singh — Electrical Maintenance Unit',
    resolved_date: '2026-03-06',
    moderated_by: 'Unit Officer Rajesh',
    moderated_at: '2026-03-07T10:15:00Z',
    public_visible: true,
    publish_status: 'published',
    view_count: 73,
  },
  {
    id: 'PUB-005',
    original_issue_id: 'ISS-DRAFT-001',
    title: 'Garbage Overflow at Sigra Market — Draft',
    category: 'Waste Management',
    ward: 'Ward 05 - Sigra',
    location: 'Sigra Market, Central Area',
    status: 'Resolved',
    summary:
      'Draft summary pending review. Garbage overflow at Sigra Market central area has been addressed. Municipal waste team cleared accumulated garbage and sanitised the area.',
    before_images: ['https://images.pexels.com/photos/2827392/pexels-photo-2827392.jpeg'],
    after_images: [],
    resolved_by: 'Field Officer Sunita Yadav — Sanitation Division',
    resolved_date: '2026-03-13',
    moderated_by: 'Unit Officer Rajesh',
    moderated_at: '2026-03-14T08:00:00Z',
    public_visible: false,
    publish_status: 'draft',
    view_count: 0,
  },
  {
    id: 'PUB-006',
    original_issue_id: 'ISS-REJECTED-001',
    title: 'Report Outside Jurisdiction — Sunderpur Bridge',
    category: 'Road Repair',
    ward: 'Ward 11 - Sunderpur',
    location: 'Sunderpur Bridge Approach Road',
    status: 'Rejected',
    summary:
      'The reported road damage near Sunderpur Bridge falls under the jurisdiction of National Highway Authority of India (NHAI) and not the municipal corporation. The issue has been forwarded to the appropriate authority.',
    before_images: [],
    after_images: [],
    resolved_by: 'N/A — Outside Jurisdiction',
    resolved_date: '2026-03-05',
    moderated_by: 'Unit Officer Rajesh',
    moderated_at: '2026-03-06T13:00:00Z',
    public_visible: false,
    publish_status: 'draft',
    rejection_reason: 'Outside Jurisdiction',
    view_count: 0,
  },
];

export const mockDuplicateGroups: DuplicateGroup[] = [
  {
    id: 'dup-001',
    citizenName: 'Priya Sharma',
    citizenPhone: '+91-98765-43210',
    detectedAt: '2026-03-14T09:30:00Z',
    similarityReason: 'Same citizen, same location, same category reported within 48 hours',
    resolved: false,
    issues: [
      {
        id: 'ISS-DUP-001A',
        title: 'Large Pothole on Assi Ghat Road',
        description:
          'There is a very large pothole on Assi Ghat Road near the market. It has been causing accidents and damaging vehicles.',
        category: 'Pothole',
        subCategories: ['Major Pothole'],
        priority: 'High',
        status: 'Pending',
        location: 'Assi Ghat Road, near vegetable market, Varanasi',
        ward: 'Varanasi Zone',
        citizenName: 'Priya Sharma',
        citizenEmail: 'priya.sharma@email.com',
        citizenPhone: '+91-98765-43210',
        dateReported: '2026-03-13T10:15:00Z',
        beforePhotos: ['https://images.pexels.com/photos/1078884/pexels-photo-1078884.jpeg'],
        issueUpdates: [],
        slaDeadline: '2026-03-20T10:15:00Z',
        coordinates: { latitude: 25.2985, longitude: 82.9961 },
        createdAt: '2026-03-13T10:15:00Z',
      },
      {
        id: 'ISS-DUP-001B',
        title: 'Deep Pothole Causing Vehicle Damage — Assi Ghat',
        description:
          'Dangerous pothole near Assi Ghat vegetable market. Multiple vehicles have been damaged. Needs urgent repair.',
        category: 'Pothole',
        subCategories: ['Major Pothole'],
        priority: 'High',
        status: 'Pending',
        location: 'Assi Ghat Road, vegetable market area, Varanasi',
        ward: 'Varanasi Zone',
        citizenName: 'Priya Sharma',
        citizenEmail: 'priya.sharma@email.com',
        citizenPhone: '+91-98765-43210',
        dateReported: '2026-03-14T08:45:00Z',
        beforePhotos: ['https://images.pexels.com/photos/1078884/pexels-photo-1078884.jpeg'],
        issueUpdates: [],
        slaDeadline: '2026-03-21T08:45:00Z',
        coordinates: { latitude: 25.2988, longitude: 82.9963 },
        createdAt: '2026-03-14T08:45:00Z',
      },
    ],
  },
  {
    id: 'dup-002',
    citizenName: 'Amit Tiwari',
    citizenPhone: '+91-99887-76655',
    detectedAt: '2026-03-14T11:00:00Z',
    similarityReason:
      'Same citizen submitted identical street light complaint twice in the same ward',
    resolved: false,
    issues: [
      {
        id: 'ISS-DUP-002A',
        title: 'Street Light Not Working — Dashashwamedh Ghat',
        description:
          'The street light near Dashashwamedh Ghat has been non-functional for over a week. The area is very dark at night.',
        category: 'Street Light',
        subCategories: ['Street Light Out'],
        priority: 'Medium',
        status: 'Verified',
        location: 'Dashashwamedh Ghat Road, Varanasi',
        ward: 'Varanasi Zone',
        citizenName: 'Amit Tiwari',
        citizenEmail: 'amit.tiwari@email.com',
        citizenPhone: '+91-99887-76655',
        dateReported: '2026-03-10T18:30:00Z',
        beforePhotos: [],
        issueUpdates: [],
        slaDeadline: '2026-03-17T18:30:00Z',
        coordinates: { latitude: 25.306, longitude: 83.0107 },
        createdAt: '2026-03-10T18:30:00Z',
      },
      {
        id: 'ISS-DUP-002B',
        title: 'No Street Light — Dashashwamedh Area is Dark',
        description:
          'Street light still broken near Dashashwamedh Ghat. Creating safety issues for evening walkers and pilgrims.',
        category: 'Street Light',
        subCategories: ['Street Light Out'],
        priority: 'Medium',
        status: 'Pending',
        location: 'Near Dashashwamedh Ghat, Varanasi',
        ward: 'Varanasi Zone',
        citizenName: 'Amit Tiwari',
        citizenEmail: 'amit.tiwari@email.com',
        citizenPhone: '+91-99887-76655',
        dateReported: '2026-03-13T19:10:00Z',
        beforePhotos: [],
        issueUpdates: [],
        slaDeadline: '2026-03-20T19:10:00Z',
        coordinates: { latitude: 25.3062, longitude: 83.0109 },
        createdAt: '2026-03-13T19:10:00Z',
      },
    ],
  },
  {
    id: 'dup-003',
    citizenName: 'Sunita Gupta',
    citizenPhone: '+91-97654-32198',
    detectedAt: '2026-03-15T07:45:00Z',
    similarityReason:
      'Three reports from same citizen about drainage overflow in same locality within 3 days',
    resolved: false,
    issues: [
      {
        id: 'ISS-DUP-003A',
        title: 'Drain Overflow Blocking Road — Lanka Chauraha',
        description:
          'Overflow from drain is blocking the main road near Lanka Chauraha. Sewage water is spreading on streets.',
        category: 'Drainage',
        subCategories: ['Drain Overflow'],
        priority: 'Critical',
        status: 'Pending',
        location: 'Lanka Chauraha, BHU Road, Varanasi',
        ward: 'Varanasi Zone',
        citizenName: 'Sunita Gupta',
        citizenEmail: 'sunita.gupta@email.com',
        citizenPhone: '+91-97654-32198',
        dateReported: '2026-03-12T07:20:00Z',
        beforePhotos: ['https://images.pexels.com/photos/1739842/pexels-photo-1739842.jpeg'],
        issueUpdates: [],
        slaDeadline: '2026-03-16T07:20:00Z',
        coordinates: { latitude: 25.2677, longitude: 82.9913 },
        createdAt: '2026-03-12T07:20:00Z',
      },
      {
        id: 'ISS-DUP-003B',
        title: 'Sewage Water on Road Near Lanka',
        description:
          'Sewage is overflowing from drain and spreading onto the road. Extremely unhygienic. Please fix immediately.',
        category: 'Drainage',
        subCategories: ['Drain Overflow'],
        priority: 'Critical',
        status: 'Pending',
        location: 'BHU Road, Lanka area, Varanasi',
        ward: 'Varanasi Zone',
        citizenName: 'Sunita Gupta',
        citizenEmail: 'sunita.gupta@email.com',
        citizenPhone: '+91-97654-32198',
        dateReported: '2026-03-14T08:55:00Z',
        beforePhotos: ['https://images.pexels.com/photos/1739842/pexels-photo-1739842.jpeg'],
        issueUpdates: [],
        slaDeadline: '2026-03-18T08:55:00Z',
        coordinates: { latitude: 25.2675, longitude: 82.9911 },
        createdAt: '2026-03-14T08:55:00Z',
      },
    ],
  },
];
